package models.count;

import annotation.TableBind;
import base.models.BaseDriverOrderStatistics;
import plugin.sqlInXml.SqlManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "driver_order_statistics")
public class DriverOrderStatistics extends BaseDriverOrderStatistics<DriverOrderStatistics> {
    public static final DriverOrderStatistics dao = new DriverOrderStatistics();
    
    
    
    public DriverOrderStatistics findByDriverId(int driverId) {
        return findFirst(SqlManager.sql("driverOrderStatistics.findByDriverId"),driverId);
    }
}
