package models.count;

import annotation.TableBind;
import base.models.BaseTaskScheduler;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "task_scheduler")
public class TaskScheduler extends BaseTaskScheduler<TaskScheduler> {
    public static final TaskScheduler dao = new TaskScheduler();
    
    
    
    
}
