package models.member;


import annotation.TableBind;
import base.models.BaseMemberPushId;
import plugin.sqlInXml.SqlManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "member_push_id")
public class MemberPushId extends BaseMemberPushId<MemberPushId> {
	public static final MemberPushId dao = new MemberPushId();
	
	public MemberPushId findByMemberId(int memberId) {
		return findFirst(SqlManager.sql("memberPush.findByMemberId"), memberId);
	}
}
