package models.member;

import annotation.TableBind;
import base.Constant;
import base.models.BaseMemberMessage;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import plugin.sqlInXml.SqlManager;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "dele_member_message")
public class MemberMessage extends BaseMemberMessage<MemberMessage> {
    public static MemberMessage dao = new MemberMessage();

    /**
     * 查询
     * @param id
     * @param date
     * @param date1
     * @return
     */
    public List<MemberMessage> findByLoginId(Integer id, Date date, Date date1) {
        return find(SqlManager.sql("memberMessage.findByLoginId"), id, date, date1);
    }
}
