package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberCar<M extends BaseMemberCar<M>> extends Model<M> implements IBean {

	public void setMember(Integer member) {
		set("member", member);
	}

	public Integer getMember() {
		return get("member");
	}

	public void setCar(Integer car) {
		set("car", car);
	}

	public Integer getCar() {
		return get("car");
	}

}
