package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {
    
    public void setId(Integer id) {
        set("id", id);
    }
    
    public Integer getId() {
        return get("id");
    }
    
    public void setNo(String no) {
        set("no", no);
    }
    
    public String getNo() {
        return get("no");
    }
    
    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }
    
    public java.util.Date getCreateTime() {
        return get("create_time");
    }
    
    public void setMember(Integer member) {
        set("member", member);
    }
    
    public Integer getMember() {
        return get("member");
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        set("amount", amount);
    }
    
    public java.math.BigDecimal getAmount() {
        return get("amount");
    }
    
    public void setDistance(java.math.BigDecimal distance) {
        set("distance", distance);
    }
    
    public java.math.BigDecimal getDistance() {
        return get("distance");
    }
    
    public void setTradeTime(java.util.Date tradeTime) {
        set("trade_time", tradeTime);
    }
    
    public java.util.Date getTradeTime() {
        return get("trade_time");
    }
    
    public void setDriver(Integer driver) {
        set("driver", driver);
    }
    
    public Integer getDriver() {
        return get("driver");
    }
    
    public void setPayChannel(Integer payChannel) {
        set("pay_channel", payChannel);
    }
    
    public Integer getPayChannel() {
        return get("pay_channel");
    }
    
    public void setStatus(Integer status) {
        set("status", status);
    }
    
    public Integer getStatus() {
        return get("status");
    }
    
    public void setType(Integer type) {
        set("type", type);
    }
    
    public Integer getType() {
        return get("type");
    }
    
    public void setLastUpdateTime(java.util.Date lastUpdateTime) {
        set("last_update_time", lastUpdateTime);
    }
    
    public java.util.Date getLastUpdateTime() {
        return get("last_update_time");
    }
    
    public void setPhone(String phone) {
        set("phone", phone);
    }
    
    public String getPhone() {
        return get("phone");
    }
    
    public void setPayTime(java.util.Date payTime) {
        set("pay_time", payTime);
    }
    
    public java.util.Date getPayTime() {
        return get("pay_time");
    }
    
    public void setSetouttime(java.util.Date setouttime) {
        set("setouttime", setouttime);
    }
    
    public java.util.Date getSetouttime() {
        return get("setouttime");
    }
    
    public void setCar(Integer car) {
        set("car", car);
    }
    
    public Integer getCar() {
        return get("car");
    }
    
    public void setRealPay(java.math.BigDecimal realPay) {
        set("real_pay", realPay);
    }
    
    public java.math.BigDecimal getRealPay() {
        return get("real_pay");
    }
    
    public void setYhAmount(java.math.BigDecimal yhAmount) {
        set("yh_amount", yhAmount);
    }
    
    public java.math.BigDecimal getYhAmount() {
        return get("yh_amount");
    }
    
    public void setYgAmount(java.math.BigDecimal ygAmount) {
        set("yg_amount", ygAmount);
    }
    
    public java.math.BigDecimal getYgAmount() {
        return get("yg_amount");
    }
    
    public void setPayStatus(Integer payStatus) {
        set("pay_status", payStatus);
    }
    
    public Integer getPayStatus() {
        return get("pay_status");
    }
    
    public void setCompany(Integer company) {
        set("company", company);
    }
    
    public Integer getCompany() {
        return get("company");
    }
    
    public void setReservationAddress(String reservationAddress) {
        set("reservation_address", reservationAddress);
    }
    
    public String getReservationAddress() {
        return get("reservation_address");
    }
    
    public void setDestination(String destination) {
        set("destination", destination);
    }
    
    public String getDestination() {
        return get("destination");
    }
    
    public void setFromType(Integer fromType) {
        set("from_type", fromType);
    }
    
    public Integer getFromType() {
        return get("from_type");
    }
    
    public void setWaitTime(java.math.BigDecimal waitTime) {
        set("wait_time", waitTime);
    }
    
    public java.math.BigDecimal getWaitTime() {
        return get("wait_time");
    }
    
    public void setConsumeTime(java.math.BigDecimal consumeTime) {
        set("consume_time", consumeTime);
    }
    
    public java.math.BigDecimal getConsumeTime() {
        return get("consume_time");
    }
    
    public void setRealDistance(java.math.BigDecimal realDistance) {
        set("real_distance", realDistance);
    }
    
    public java.math.BigDecimal getRealDistance() {
        return get("real_distance");
    }
    
    public void setWaitDistance(java.math.BigDecimal waitDistance) {
        set("wait_distance", waitDistance);
    }
    
    public java.math.BigDecimal getWaitDistance() {
        return get("wait_distance");
    }
    
    public void setDelFlag(Boolean delFlag) {
        set("del_flag", delFlag);
    }
    
    public Boolean getDelFlag() {
        return get("del_flag");
    }
    
    public void setPdFlag(Boolean pdFlag) {
        set("pd_flag", pdFlag);
    }
    
    public Boolean getPdFlag() {
        return get("pd_flag");
    }
    
    public void setServiceType(Integer serviceType) {
        set("service_type", serviceType);
    }
    
    public Integer getServiceType() {
        return get("service_type");
    }
    
    public void setSetOutFlag(Boolean setOutFlag) {
        set("set_out_flag", setOutFlag);
    }
    
    public Boolean getSetOutFlag() {
        return get("set_out_flag");
    }
    
    public void setBaseAmount(java.math.BigDecimal baseAmount) {
        set("base_amount", baseAmount);
    }
    
    public java.math.BigDecimal getBaseAmount() {
        return get("base_amount");
    }
    
    public void setTag(String tag) {
        set("tag", tag);
    }
    
    public String getTag() {
        return get("tag");
    }
    
    public void setRemark(String remark) {
        set("remark", remark);
    }
    
    public String getRemark() {
        return get("remark");
    }
    
    public void setDistanceAmount(java.math.BigDecimal distanceAmount) {
        set("distance_amount", distanceAmount);
    }
    
    public java.math.BigDecimal getDistanceAmount() {
        return get("distance_amount");
    }
    
    public void setTimeOutAmount(java.math.BigDecimal timeOutAmount) {
        set("time_out_amount", timeOutAmount);
    }
    
    public java.math.BigDecimal getTimeOutAmount() {
        return get("time_out_amount");
    }
    
    public void setRoadToll(java.math.BigDecimal roadToll) {
        set("road_toll", roadToll);
    }
    
    public java.math.BigDecimal getRoadToll() {
        return get("road_toll");
    }
    
    public void setRemoteFee(java.math.BigDecimal remoteFee) {
        set("remote_fee", remoteFee);
    }
    
    public java.math.BigDecimal getRemoteFee() {
        return get("remote_fee");
    }
    
    public void setOtherCharges(java.math.BigDecimal otherCharges) {
        set("other_charges", otherCharges);
    }
    
    public java.math.BigDecimal getOtherCharges() {
        return get("other_charges");
    }
    
    public void setWaitAmount(java.math.BigDecimal waitAmount) {
        set("wait_amount", waitAmount);
    }
    
    public java.math.BigDecimal getWaitAmount() {
        return get("wait_amount");
    }
    
    public void setCoupon(Integer coupon) {
        set("coupon", coupon);
    }
    
    public Integer getCoupon() {
        return get("coupon");
    }
    
    public void setFromCompany(Integer fromCompany) {
        set("from_company", fromCompany);
    }
    
    public Integer getFromCompany() {
        return get("from_company");
    }
    
    public void setAddAmount(java.math.BigDecimal addAmount) {
        set("add_amount", addAmount);
    }
    
    public java.math.BigDecimal getAddAmount() {
        return get("add_amount");
    }
    
    public void setAddFlag(Boolean addFlag) {
        set("add_flag", addFlag);
    }
    
    public Boolean getAddFlag() {
        return get("add_flag");
    }
    
    public void setPeople(Integer people) {
        set("people", people);
    }
    
    public Integer getPeople() {
        return get("people");
    }
    
    public void setZxLine(Integer zxLine) {
        set("zx_line", zxLine);
    }
    
    public Integer getZxLine() {
        return get("zx_line");
    }
    
    public void setTraverId(Integer traverId) {
        set("traverId", traverId);
    }
    
    public Integer getTraverId() {
        return get("traverId");
    }
    
    public void setVehicleNo(String VehicleNo) {
        set("VehicleNo", VehicleNo);
    }
    
    public String getVehicleNo() {
        return get("VehicleNo");
    }
    
    public void setOrderIp(String orderIp) {
        set("order_ip", orderIp);
    }
    
    public String getOrderIp() {
        return get("order_ip");
    }
    
    public void setOrderImsi(String orderImsi) {
        set("order_IMSI", orderImsi);
    }
    
    public String getOrderImsi() {
        return get("order_IMSI");
    }
    
    public void setOrderImei(String orderImei) {
        set("order_IMEI", orderImei);
    }
    
    public String getOrderImei() {
        return get("order_IMEI");
    }
    
    public void setMacAddress(String macAddress) {
        set("mac_address", macAddress);
    }
    
    public String getMacAddress() {
        return get("mac_address");
    }
    
    public void setPort(String port) {
        set("port", port);
    }
    
    public String getPort() {
        return get("port");
    }
    
    public void setVipActivityFlag(Integer vipActivityFlag) {
        set("vip_activity_flag", vipActivityFlag);
    }
    
    public Integer getVipActivityFlag() {
        return get("vip_activity_flag");
    }
    
    public void setAutoDispatchOrder(Integer autoDispatchOrder) {
        set("auto_dispatch_order", autoDispatchOrder);
    }
    
    public Integer getAutoDispatchOrder() {
        return get("auto_dispatch_order");
    }
    
    public void setByMeter(Integer byMeter) {
        set("by_meter", byMeter);
    }
    
    public Integer getByMeter() {
        return get("by_meter");
    }

    public void setFlightNo(String flightNo) {
        set("flight_no", flightNo);
    }

    public String getFlightNo() {
        return get("flight_no");
    }
}
