package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberPushId<M extends BaseMemberPushId<M>> extends Model<M> implements IBean {
    
    public void setId(Integer id) {
        set("id", id);
    }
    
    public Integer getId() {
        return get("id");
    }
    
    public void setMemberId(Integer memberId) {
        set("member_id", memberId);
    }
    
    public Integer getMemberId() {
        return get("member_id");
    }
    
    public void setRegistrationId(String registrationId) {
        set("registrationId", registrationId);
    }
    
    public String getRegistrationId() {
        return get("registrationId");
    }
    
    public void setCId(String cId) {
        set("cId", cId);
    }
    
    public String getCId() {
        return get("cId");
    }
    
    public void setDeviceId(String deviceId) {
        set("deviceId", deviceId);
    }
    
    public String getDeviceId() {
        return get("deviceId");
    }
    
    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }
    
    public java.util.Date getCreateTime() {
        return get("create_time");
    }
    
    public void setUpdateTime(java.util.Date updateTime) {
        set("update_time", updateTime);
    }
    
    public java.util.Date getUpdateTime() {
        return get("update_time");
    }
    
    
    public void setDeviceType(Integer deviceType) {
        set("device_type", deviceType);
    }
    
    public Integer getDeviceType() {
        return get("device_type");
    }
    
}
