package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrade<M extends BaseGrade<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setMasterId(Integer masterId) {
		set("master_id", masterId);
	}

	public Integer getMasterId() {
		return get("master_id");
	}

	public void setMemberId(Integer memberId) {
		set("member_id", memberId);
	}

	public Integer getMemberId() {
		return get("member_id");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setScore(Double score) {
		set("score", score);
	}

	public Double getScore() {
		return get("score");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setOrder(Integer order) {
		set("order_id", order);
	}

	public Integer getOrder() {
		return get("order_id");
	}

}
