package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarBrand<M extends BaseCarBrand<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setLogo(String logo) {
		set("logo", logo);
	}

	public String getLogo() {
		return get("logo");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPyName(String pyName) {
		set("py_name", pyName);
	}

	public String getPyName() {
		return get("py_name");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return get("description");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setFristPy(String fristPy) {
		set("frist_py", fristPy);
	}

	public String getFristPy() {
		return get("frist_py");
	}

}
