package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAd<M extends BaseAd<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setPic(String pic) {
		set("pic", pic);
	}

	public String getPic() {
		return get("pic");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setDefaultFlag(Boolean defaultFlag) {
		set("default_flag", defaultFlag);
	}

	public Boolean getDefaultFlag() {
		return get("default_flag");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}

	public Integer getSort() {
		return get("sort");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setAppType(Integer appType) {
		set("app_type", appType);
	}

	public Integer getAppType() {
		return get("app_type");
	}

	public void setLastUpdate(java.util.Date lastUpdate) {
		set("last_update", lastUpdate);
	}

	public java.util.Date getLastUpdate() {
		return get("last_update");
	}

}
