package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverRebate<M extends BaseDriverRebate<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setOrderId(Integer orderId) {
		set("order_id", orderId);
	}

	public Integer getOrderId() {
		return get("order_id");
	}

	public void setRebateTime(java.util.Date rebateTime) {
		set("rebate_time", rebateTime);
	}

	public java.util.Date getRebateTime() {
		return get("rebate_time");
	}

	public void setDriver(Integer driver) {
		set("driver", driver);
	}

	public Integer getDriver() {
		return get("driver");
	}

}
