package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberCapitalAccount<M extends BaseMemberCapitalAccount<M>> extends Model<M> implements IBean {

	public void setLoginId(Integer loginId) {
		set("login_id", loginId);
	}

	public Integer getLoginId() {
		return get("login_id");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("last_update_time", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("last_update_time");
	}

	public void setLastUpdateAmount(java.math.BigDecimal lastUpdateAmount) {
		set("last_update_amount", lastUpdateAmount);
	}

	public java.math.BigDecimal getLastUpdateAmount() {
		return get("last_update_amount");
	}

	public void setAccount(String account) {
		set("account", account);
	}

	public String getAccount() {
		return get("account");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setAlipayAccount(String alipayAccount) {
		set("alipay_account", alipayAccount);
	}

	public String getAlipayAccount() {
		return get("alipay_account");
	}

	public void setAlipayRealName(String alipayRealName) {
		set("alipay_real_name", alipayRealName);
	}

	public String getAlipayRealName() {
		return get("alipay_real_name");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setTxAmount(java.math.BigDecimal txAmount) {
		set("tx_amount", txAmount);
	}

	public java.math.BigDecimal getTxAmount() {
		return get("tx_amount");
	}

	public void setLastUpdateTxAmount(java.math.BigDecimal lastUpdateTxAmount) {
		set("last_update_tx_amount", lastUpdateTxAmount);
	}

	public java.math.BigDecimal getLastUpdateTxAmount() {
		return get("last_update_tx_amount");
	}

}
