package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInvoiceOrder<M extends BaseInvoiceOrder<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setInvoiceId(Integer invoiceId) {
		set("invoice_id", invoiceId);
	}

	public Integer getInvoiceId() {
		return get("invoice_id");
	}

	public void setOrderId(Integer orderId) {
		set("order_id", orderId);
	}

	public Integer getOrderId() {
		return get("order_id");
	}

}
