package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInvoiceRec<M extends BaseInvoiceRec<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setInvoiceHeader(String invoiceHeader) {
		set("invoice_header", invoiceHeader);
	}

	public String getInvoiceHeader() {
		return get("invoice_header");
	}

	public void setInvoiceNo(String invoiceNo) {
		set("invoice_no", invoiceNo);
	}

	public String getInvoiceNo() {
		return get("invoice_no");
	}

	public void setPic(String pic) {
		set("pic", pic);
	}

	public String getPic() {
		return get("pic");
	}

	public void setInvoiceTime(java.util.Date invoiceTime) {
		set("invoice_time", invoiceTime);
	}

	public java.util.Date getInvoiceTime() {
		return get("invoice_time");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setPostCode(String postCode) {
		set("post_code", postCode);
	}

	public String getPostCode() {
		return get("post_code");
	}

	public void setPostAddress(String postAddress) {
		set("post_address", postAddress);
	}

	public String getPostAddress() {
		return get("post_address");
	}

	public void setAddressee(String addressee) {
		set("addressee", addressee);
	}

	public String getAddressee() {
		return get("addressee");
	}

	public void setAddresseePhone(String addresseePhone) {
		set("addressee_phone", addresseePhone);
	}

	public String getAddresseePhone() {
		return get("addressee_phone");
	}

	public void setExpressNo(String expressNo) {
		set("express_no", expressNo);
	}

	public String getExpressNo() {
		return get("express_no");
	}

	public void setExpressCompany(String expressCompany) {
		set("express_company", expressCompany);
	}

	public String getExpressCompany() {
		return get("express_company");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setLoginId(Integer loginId) {
		set("login_id", loginId);
	}

	public Integer getLoginId() {
		return get("login_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
