package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setAdcode(String adcode) {
		set("adcode", adcode);
	}

	public String getAdcode() {
		return get("adcode");
	}

	public void setCitycode(String citycode) {
		set("citycode", citycode);
	}

	public String getCitycode() {
		return get("citycode");
	}

	public void setLevel(String level) {
		set("level", level);
	}

	public String getLevel() {
		return get("level");
	}

	public void setParent(String parent) {
		set("parent", parent);
	}

	public String getParent() {
		return get("parent");
	}

}
