package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAlipayLog<M extends BaseAlipayLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setNotifyTime(String notifyTime) {
		set("notify_time", notifyTime);
	}

	public String getNotifyTime() {
		return get("notify_time");
	}

	public void setNotifyType(String notifyType) {
		set("notify_type", notifyType);
	}

	public String getNotifyType() {
		return get("notify_type");
	}

	public void setNotifyId(String notifyId) {
		set("notify_id", notifyId);
	}

	public String getNotifyId() {
		return get("notify_id");
	}

	public void setAppId(String appId) {
		set("app_id", appId);
	}

	public String getAppId() {
		return get("app_id");
	}

	public void setSignType(String signType) {
		set("sign_type", signType);
	}

	public String getSignType() {
		return get("sign_type");
	}

	public void setSign(String sign) {
		set("sign", sign);
	}

	public String getSign() {
		return get("sign");
	}

	public void setTradeNo(String tradeNo) {
		set("trade_no", tradeNo);
	}

	public String getTradeNo() {
		return get("trade_no");
	}

	public void setOutTradeNo(String outTradeNo) {
		set("out_trade_no", outTradeNo);
	}

	public String getOutTradeNo() {
		return get("out_trade_no");
	}

	public void setOutBizNo(String outBizNo) {
		set("out_biz_no", outBizNo);
	}

	public String getOutBizNo() {
		return get("out_biz_no");
	}

	public void setBuyerId(String buyerId) {
		set("buyer_id", buyerId);
	}

	public String getBuyerId() {
		return get("buyer_id");
	}

	public void setBuyerLogonId(String buyerLogonId) {
		set("buyer_logon_id", buyerLogonId);
	}

	public String getBuyerLogonId() {
		return get("buyer_logon_id");
	}

	public void setSellerId(String sellerId) {
		set("seller_id", sellerId);
	}

	public String getSellerId() {
		return get("seller_id");
	}

	public void setSellerEmail(String sellerEmail) {
		set("seller_email", sellerEmail);
	}

	public String getSellerEmail() {
		return get("seller_email");
	}

	public void setTradeStatus(String tradeStatus) {
		set("trade_status", tradeStatus);
	}

	public String getTradeStatus() {
		return get("trade_status");
	}

	public void setTotalAmount(String totalAmount) {
		set("total_amount", totalAmount);
	}

	public String getTotalAmount() {
		return get("total_amount");
	}

	public void setReceiptAmount(String receiptAmount) {
		set("receipt_amount", receiptAmount);
	}

	public String getReceiptAmount() {
		return get("receipt_amount");
	}

	public void setInvoiceAmount(String invoiceAmount) {
		set("invoice_amount", invoiceAmount);
	}

	public String getInvoiceAmount() {
		return get("invoice_amount");
	}

	public void setBuyerPayAmount(String buyerPayAmount) {
		set("buyer_pay_amount", buyerPayAmount);
	}

	public String getBuyerPayAmount() {
		return get("buyer_pay_amount");
	}

	public void setPointAmount(String pointAmount) {
		set("point_amount", pointAmount);
	}

	public String getPointAmount() {
		return get("point_amount");
	}

	public void setRefundFee(String refundFee) {
		set("refund_fee", refundFee);
	}

	public String getRefundFee() {
		return get("refund_fee");
	}

	public void setSubject(String subject) {
		set("subject", subject);
	}

	public String getSubject() {
		return get("subject");
	}

	public void setBody(String body) {
		set("body", body);
	}

	public String getBody() {
		return get("body");
	}

	public void setGmtCreate(String gmtCreate) {
		set("gmt_create", gmtCreate);
	}

	public String getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtPayment(String gmtPayment) {
		set("gmt_payment", gmtPayment);
	}

	public String getGmtPayment() {
		return get("gmt_payment");
	}

	public void setGmtRefund(String gmtRefund) {
		set("gmt_refund", gmtRefund);
	}

	public String getGmtRefund() {
		return get("gmt_refund");
	}

	public void setGmtClose(String gmtClose) {
		set("gmt_close", gmtClose);
	}

	public String getGmtClose() {
		return get("gmt_close");
	}

	public void setFundBillList(String fundBillList) {
		set("fund_bill_list", fundBillList);
	}

	public String getFundBillList() {
		return get("fund_bill_list");
	}

}
