package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseinfoCompany<M extends BaseBaseinfoCompany<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCompanyId(String companyId) {
		set("companyId", companyId);
	}

	public String getCompanyId() {
		return get("companyId");
	}

	public void setCompanyname(String companyname) {
		set("companyname", companyname);
	}

	public String getCompanyname() {
		return get("companyname");
	}

	public void setIdentifier(String identifier) {
		set("identifier", identifier);
	}

	public String getIdentifier() {
		return get("identifier");
	}

	public void setAddress(Integer address) {
		set("address", address);
	}

	public Integer getAddress() {
		return get("address");
	}

	public void setBusinessscope(String businessscope) {
		set("businessscope", businessscope);
	}

	public String getBusinessscope() {
		return get("businessscope");
	}

	public void setContactaddress(String contactaddress) {
		set("contactaddress", contactaddress);
	}

	public String getContactaddress() {
		return get("contactaddress");
	}

	public void setEconomictype(String economictype) {
		set("economictype", economictype);
	}

	public String getEconomictype() {
		return get("economictype");
	}

	public void setRegcapital(String regcapital) {
		set("regcapital", regcapital);
	}

	public String getRegcapital() {
		return get("regcapital");
	}

	public void setLegalname(String legalname) {
		set("legalname", legalname);
	}

	public String getLegalname() {
		return get("legalname");
	}

	public void setLegalid(String legalid) {
		set("legalid", legalid);
	}

	public String getLegalid() {
		return get("legalid");
	}

	public void setLegalphone(String legalphone) {
		set("legalphone", legalphone);
	}

	public String getLegalphone() {
		return get("legalphone");
	}

	public void setState(Integer state) {
		set("state", state);
	}

	public Integer getState() {
		return get("state");
	}

	public void setFlag(Integer flag) {
		set("flag", flag);
	}

	public Integer getFlag() {
		return get("flag");
	}

	public void setUpdatetime(Integer updatetime) {
		set("updatetime", updatetime);
	}

	public Integer getUpdatetime() {
		return get("updatetime");
	}

}
