package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraverRecord<M extends BaseTraverRecord<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setStartLongitude(Double startLongitude) {
		set("start_longitude", startLongitude);
	}

	public Double getStartLongitude() {
		return get("start_longitude");
	}

	public void setStartLatitude(Double startLatitude) {
		set("start_latitude", startLatitude);
	}

	public Double getStartLatitude() {
		return get("start_latitude");
	}

	public void setEndLongitude(Double endLongitude) {
		set("end_longitude", endLongitude);
	}

	public Double getEndLongitude() {
		return get("end_longitude");
	}

	public void setEndLatitude(Double endLatitude) {
		set("end_latitude", endLatitude);
	}

	public Double getEndLatitude() {
		return get("end_latitude");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setSetoutTime1(java.util.Date setoutTime1) {
		set("setout_time1", setoutTime1);
	}

	public java.util.Date getSetoutTime1() {
		return get("setout_time1");
	}

	public void setSetoutTime2(java.util.Date setoutTime2) {
		set("setout_time2", setoutTime2);
	}

	public java.util.Date getSetoutTime2() {
		return get("setout_time2");
	}

	public void setYgAmount(java.math.BigDecimal ygAmount) {
		set("yg_amount", ygAmount);
	}

	public java.math.BigDecimal getYgAmount() {
		return get("yg_amount");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setStartAdcode(String startAdcode) {
		set("start_adcode", startAdcode);
	}

	public String getStartAdcode() {
		return get("start_adcode");
	}

	public void setEndAdcode(String endAdcode) {
		set("end_adcode", endAdcode);
	}

	public String getEndAdcode() {
		return get("end_adcode");
	}

	public void setDistance(java.math.BigDecimal distance) {
		set("distance", distance);
	}

	public java.math.BigDecimal getDistance() {
		return get("distance");
	}

	public void setYjTime(java.math.BigDecimal yjTime) {
		set("yj_time", yjTime);
	}

	public java.math.BigDecimal getYjTime() {
		return get("yj_time");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setFlag(Boolean flag) {
		set("flag", flag);
	}

	public Boolean getFlag() {
		return get("flag");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setPeople(Integer people) {
		set("people", people);
	}

	public Integer getPeople() {
		return get("people");
	}

	public void setTag(String tag) {
		set("tag", tag);
	}

	public String getTag() {
		return get("tag");
	}

	public void setDriverId(Integer driverId) {
		set("driverId", driverId);
	}

	public Integer getDriverId() {
		return get("driverId");
	}

	public void setMemberId(Integer memberId) {
		set("memberId", memberId);
	}

	public Integer getMemberId() {
		return get("memberId");
	}

	public void setReservationAddress(String reservationAddress) {
		set("reservationAddress", reservationAddress);
	}

	public String getReservationAddress() {
		return get("reservationAddress");
	}

	public void setDestination(String destination) {
		set("destination", destination);
	}

	public String getDestination() {
		return get("destination");
	}

	public void setReservationCity(String reservationCity) {
		set("reservationCity", reservationCity);
	}

	public String getReservationCity() {
		return get("reservationCity");
	}

	public void setDestinationCity(String destinationCity) {
		set("destinationCity", destinationCity);
	}

	public String getDestinationCity() {
		return get("destinationCity");
	}

	public void setPinCheAmount(java.math.BigDecimal pinCheAmount) {
		set("pinCheAmount", pinCheAmount);
	}

	public java.math.BigDecimal getPinCheAmount() {
		return get("pinCheAmount");
	}

	public void setJiHuoAmount(java.math.BigDecimal jiHuoAmount) {
		set("jiHuoAmount", jiHuoAmount);
	}

	public java.math.BigDecimal getJiHuoAmount() {
		return get("jiHuoAmount");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setRecordType(Integer recordType) {
		set("record_type", recordType);
	}

	public Integer getRecordType() {
		return get("record_type");
	}

	public void setTotalPeople(Integer totalPeople) {
		set("totalPeople", totalPeople);
	}

	public Integer getTotalPeople() {
		return get("totalPeople");
	}

	public void setConsigneeName(String consigneeName) {
		set("consigneeName", consigneeName);
	}

	public String getConsigneeName() {
		return get("consigneeName");
	}

	public void setConsigneePhone(String consigneePhone) {
		set("consigneePhone", consigneePhone);
	}

	public String getConsigneePhone() {
		return get("consigneePhone");
	}

	public void setMess(String mess) {
		set("mess", mess);
	}

	public String getMess() {
		return get("mess");
	}


	public void setCompleted(Integer completed) {
		set("completed", completed);
	}

	public Integer getCompleted() {
		return get("completed");
	}

}
