package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarInfo<M extends BaseCarInfo<M>> extends Model<M> implements IBean {

	public void setCarId(Integer carId) {
		set("car_id", carId);
	}

	public Integer getCarId() {
		return get("car_id");
	}

	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}

	public java.util.Date getJoinTime() {
		return get("join_time");
	}

	public void setProvince(String province) {
		set("province", province);
	}

	public String getProvince() {
		return get("province");
	}

	public void setCity(String city) {
		set("city", city);
	}

	public String getCity() {
		return get("city");
	}

	public void setCounty(String county) {
		set("county", county);
	}

	public String getCounty() {
		return get("county");
	}

	public void setDistance(Long distance) {
		set("distance", distance);
	}

	public Long getDistance() {
		return get("distance");
	}

}
