package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoyaltyStandardEasy<M extends BaseRoyaltyStandardEasy<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setRoyaltyStandard(Integer royaltyStandard) {
		set("royalty_standard", royaltyStandard);
	}

	public Integer getRoyaltyStandard() {
		return get("royalty_standard");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setFixedMoney(java.math.BigDecimal fixedMoney) {
		set("fixed_money", fixedMoney);
	}

	public java.math.BigDecimal getFixedMoney() {
		return get("fixed_money");
	}

	public void setLessThanMoney1(java.math.BigDecimal lessThanMoney1) {
		set("less_than_money1", lessThanMoney1);
	}

	public java.math.BigDecimal getLessThanMoney1() {
		return get("less_than_money1");
	}

	public void setGetMoney1(java.math.BigDecimal getMoney1) {
		set("get_money1", getMoney1);
	}

	public java.math.BigDecimal getGetMoney1() {
		return get("get_money1");
	}

	public void setRatio(java.math.BigDecimal ratio) {
		set("ratio", ratio);
	}

	public java.math.BigDecimal getRatio() {
		return get("ratio");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setLessThanMoney2(java.math.BigDecimal lessThanMoney2) {
		set("less_than_money2", lessThanMoney2);
	}

	public java.math.BigDecimal getLessThanMoney2() {
		return get("less_than_money2");
	}

	public void setGetMoney2(java.math.BigDecimal getMoney2) {
		set("get_money2", getMoney2);
	}

	public java.math.BigDecimal getGetMoney2() {
		return get("get_money2");
	}

}
