package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverPunish<M extends BaseDriverPunish<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setDriverId(Integer driverId) {
		set("driver_id", driverId);
	}

	public Integer getDriverId() {
		return get("driver_id");
	}

	public void setPunishTime(java.util.Date PunishTime) {
		set("PunishTime", PunishTime);
	}

	public java.util.Date getPunishTime() {
		return get("PunishTime");
	}

	public void setPunishResult(String PunishResult) {
		set("PunishResult", PunishResult);
	}

	public String getPunishResult() {
		return get("PunishResult");
	}

	public void setPunishReason(String PunishReason) {
		set("PunishReason", PunishReason);
	}

	public String getPunishReason() {
		return get("PunishReason");
	}

}
