package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberComplain<M extends BaseMemberComplain<M>> extends Model<M> implements IBean {

    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }

    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    public String getCompanyId() {
        return get("CompanyId");
    }

    public void setOrderId(String OrderId) {
        set("OrderId", OrderId);
    }

    public String getOrderId() {
        return get("OrderId");
    }

    public void setComplaintTime(Long ComplaintTime) {
        set("ComplaintTime", ComplaintTime);
    }

    public Long getComplaintTime() {
        return get("ComplaintTime");
    }

    public void setDetail(String Detail) {
        set("Detail", Detail);
    }

    public String getDetail() {
        return get("Detail");
    }

    public void setResult(String Result) {
        set("Result", Result);
    }

    public String getResult() {
        return get("Result");
    }

}
