package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoyaltyStandardMoneyItem<M extends BaseRoyaltyStandardMoneyItem<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setParent(Integer parent) {
		set("parent", parent);
	}

	public Integer getParent() {
		return get("parent");
	}

	public void setStartMoney(java.math.BigDecimal startMoney) {
		set("start_money", startMoney);
	}

	public java.math.BigDecimal getStartMoney() {
		return get("start_money");
	}

	public void setEndMoney(java.math.BigDecimal endMoney) {
		set("end_money", endMoney);
	}

	public java.math.BigDecimal getEndMoney() {
		return get("end_money");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setEachMoney(java.math.BigDecimal eachMoney) {
		set("each_money", eachMoney);
	}

	public java.math.BigDecimal getEachMoney() {
		return get("each_money");
	}

	public void setGetMoney(java.math.BigDecimal getMoney) {
		set("get_money", getMoney);
	}

	public java.math.BigDecimal getGetMoney() {
		return get("get_money");
	}

	public void setRoyaltyStandard(Integer royaltyStandard) {
		set("royalty_standard", royaltyStandard);
	}

	public Integer getRoyaltyStandard() {
		return get("royalty_standard");
	}

}
