package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyAccount<M extends BaseCompanyAccount<M>> extends Model<M> implements IBean {

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setAlipayAccount(String alipayAccount) {
		set("alipay_account", alipayAccount);
	}

	public String getAlipayAccount() {
		return get("alipay_account");
	}

	public void setBankAccount(String bankAccount) {
		set("bank_account", bankAccount);
	}

	public String getBankAccount() {
		return get("bank_account");
	}

	public void setLastAmont(java.math.BigDecimal lastAmont) {
		set("last_amont", lastAmont);
	}

	public java.math.BigDecimal getLastAmont() {
		return get("last_amont");
	}

	public void setLastUpdate(java.util.Date lastUpdate) {
		set("last_update", lastUpdate);
	}

	public java.util.Date getLastUpdate() {
		return get("last_update");
	}

	public void setSmsCount(Integer smsCount) {
		set("sms_count", smsCount);
	}

	public Integer getSmsCount() {
		return get("sms_count");
	}

	public void setActivityAmount(java.math.BigDecimal activityAmount) {
		set("activity_amount", activityAmount);
	}

	public java.math.BigDecimal getActivityAmount() {
		return get("activity_amount");
	}

	public void setInsuranceAmount(java.math.BigDecimal insuranceAmount) {
		set("insurance_amount", insuranceAmount);
	}

	public java.math.BigDecimal getInsuranceAmount() {
		return get("insurance_amount");
	}

}
