package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminSetting<M extends BaseAdminSetting<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return get("id");
    }

    public void setCompanyId(Integer companyId) {
        set("companyId", companyId);
    }

    public Integer getCompanyId() {
        return get("companyId");
    }

    public void setOrderReciveTime(Integer orderReciveTime) {
        set("order_recive_time", orderReciveTime);
    }

    public Integer getOrderReciveTime() {
        return get("order_recive_time");
    }

    public void setMinAmount(Integer minAmount) {
        set("min_amount", minAmount);
    }

    public Integer getMinAmount() {
        return get("min_amount");
    }

    public void setDepositAmount1(Integer depositAmount1) {
        set("deposit_amount1", depositAmount1);
    }

    public Integer getDepositAmount1() {
        return get("deposit_amount1");
    }

    public void setDepositAmount2(Integer depositAmount2) {
        set("deposit_amount2", depositAmount2);
    }

    public Integer getDepositAmount2() {
        return get("deposit_amount2");
    }

    public void setDepositAmount3(Integer depositAmount3) {
        set("deposit_amount3", depositAmount3);
    }

    public Integer getDepositAmount3() {
        return get("deposit_amount3");
    }

    public void setAutoDispatch(Boolean autoDispatch) {
        set("auto_dispatch", autoDispatch);
    }

    public Boolean getAutoDispatch() {
        return get("auto_dispatch");
    }

    public void setDispatchMill1(String dispatchMill1) {
        set("dispatch_mill1", dispatchMill1);
    }

    public Double getDispatchMill1() {
        return get("dispatch_mill1");
    }

    public void setDispatchTimeOut1(Integer dispatchTimeOut1) {
        set("dispatch_time_out1", dispatchTimeOut1);
    }

    public Integer getDispatchTimeOut1() {
        return get("dispatch_time_out1");
    }

    public void setDispatchMill2(String dispatchMill2) {
        set("dispatch_mill2", dispatchMill2);
    }

    public Double getDispatchMill2() {
        return get("dispatch_mill2");
    }

    public void setDispatchTimeOut2(Integer dispatchTimeOut2) {
        set("dispatch_time_out2", dispatchTimeOut2);
    }

    public Integer getDispatchTimeOut2() {
        return get("dispatch_time_out2");
    }

    public void setDispatchMill3(String dispatchMill3) {
        set("dispatch_mill3", dispatchMill3);
    }

    public Double getDispatchMill3() {
        return get("dispatch_mill3");
    }

    public void setDispatchTimeOut3(Integer dispatchTimeOut3) {
        set("dispatch_time_out3", dispatchTimeOut3);
    }

    public Integer getDispatchTimeOut3() {
        return get("dispatch_time_out3");
    }

    public void setGrabSingleFlag(Boolean grabSingleFlag) {
        set("grab_single_flag", grabSingleFlag);
    }

    public Boolean getGrabSingleFlag() {
        return get("grab_single_flag");
    }

    public void setGrabSingleMill1(String grabSingleMill1) {
        set("grab_single_mill1", grabSingleMill1);
    }

    public Double getGrabSingleMill1() {
        String str = get("grab_single_mill1").toString();
        if(!str.contains(".")){
            str = str +".0";
        }
        return Double.valueOf(str);
    }

    public void setGrabSingleTimeOut1(Integer grabSingleTimeOut1) {
        set("grab_single_time_out1", grabSingleTimeOut1);
    }

    public Integer getGrabSingleTimeOut1() {
        return get("grab_single_time_out1");
    }

    public void setGrabSingleMill2(String grabSingleMill2) {
        set("grab_single_mill2", grabSingleMill2);
    }

    public Double getGrabSingleMill2() {
        String str = get("grab_single_mill2").toString();
        if(!str.contains(".")){
            str = str +".0";
        }
        return Double.valueOf(str);
    }

    public void setGrabSingleTimeOut2(Integer grabSingleTimeOut2) {
        set("grab_single_time_out2", grabSingleTimeOut2);
    }

    public Integer getGrabSingleTimeOut2() {
        return get("grab_single_time_out2");
    }

    public void setGrabSingleMill3(String grabSingleMill3) {
        set("grab_single_mill3", grabSingleMill3);
    }

    public Double getGrabSingleMill3() {
        String str = get("grab_single_mill3").toString();
        if(!str.contains(".")){
            str = str +".0";
        }
        return Double.valueOf(str);
    }

    public void setGrabSingleTimeOut3(Integer grabSingleTimeOut3) {
        set("grab_single_time_out3", grabSingleTimeOut3);
    }

    public Integer getGrabSingleTimeOut3() {
        return get("grab_single_time_out3");
    }

    public void setChangeOrderFlag(Boolean changeOrderFlag) {
        set("change_order_flag", changeOrderFlag);
    }

    public Boolean getChangeOrderFlag() {
        return get("change_order_flag");
    }

    public void setCustomerInfoFlag(Boolean customerInfoFlag) {
        set("customer_info_flag", customerInfoFlag);
    }

    public Boolean getCustomerInfoFlag() {
        return get("customer_info_flag");
    }

    public void setCarpoolFlag(Boolean carpoolFlag) {
        set("carpool_flag", carpoolFlag);
    }

    public Boolean getCarpoolFlag() {
        return get("carpool_flag");
    }

    public void setCarpoolRebat(java.math.BigDecimal carpoolRebat) {
        set("carpool_rebat", carpoolRebat);
    }

    public java.math.BigDecimal getCarpoolRebat() {
        return get("carpool_rebat");
    }

    public void setBindDeviceFlag(Boolean bindDeviceFlag) {
        set("bind_device_flag", bindDeviceFlag);
    }

    public Boolean getBindDeviceFlag() {
        return get("bind_device_flag");
    }

    public void setInsuranceAmount(java.math.BigDecimal insuranceAmount) {
        set("insurance_amount", insuranceAmount);
    }

    public java.math.BigDecimal getInsuranceAmount() {
        return get("insurance_amount");
    }

    public void setKcInsuranceAmount(java.math.BigDecimal kcInsuranceAmount) {
        set("kc_insurance_amount", kcInsuranceAmount);
    }

    public java.math.BigDecimal getKcInsuranceAmount() {
        return get("kc_insurance_amount");
    }

    public void setCzInsuranceAmount(java.math.BigDecimal czInsuranceAmount) {
        set("cz_insurance_amount", czInsuranceAmount);
    }

    public java.math.BigDecimal getCzInsuranceAmount() {
        return get("cz_insurance_amount");
    }

    public void setHhInsuranceAmount(java.math.BigDecimal hhInsuranceAmount) {
        set("hh_insurance_amount", hhInsuranceAmount);
    }

    public java.math.BigDecimal getHhInsuranceAmount() {
        return get("hh_insurance_amount");
    }

    public void setSsInsuranceAmount(java.math.BigDecimal ssInsuranceAmount) {
        set("ss_insurance_amount", ssInsuranceAmount);
    }

    public java.math.BigDecimal getSsInsuranceAmount() {
        return get("ss_insurance_amount");
    }

    public void setDjInsuranceAmount(java.math.BigDecimal djInsuranceAmount) {
        set("dj_insurance_amount", djInsuranceAmount);
    }

    public java.math.BigDecimal getDjInsuranceAmount() {
        return get("dj_insurance_amount");
    }

    public void setSwInsuranceAmount(java.math.BigDecimal swInsuranceAmount) {
        set("sw_insurance_amount", swInsuranceAmount);
    }

    public java.math.BigDecimal getSwInsuranceAmount() {
        return get("sw_insurance_amount");
    }

    public void setVipAmount(java.math.BigDecimal vipAmount) {
        set("vip_amount", vipAmount);
    }

    public java.math.BigDecimal getVipAmount() {
        return get("vip_amount");
    }

    public void setVipSingleSpendingAmount(java.math.BigDecimal vipSingleSpendingAmount) {
        set("vip_single_spending_amount", vipSingleSpendingAmount);
    }

    public java.math.BigDecimal getVipSingleSpendingAmount() {
        return get("vip_single_spending_amount");
    }

    public void setZxHkDispatch(Integer zxHkDispatch) {
        set("zx_hk_dispatch", zxHkDispatch);
    }

    public Integer getZxHkDispatch() {
        return get("zx_hk_dispatch");
    }

    public void setZxCjDispatch(Integer zxCjDispatch) {
        set("zx_cj_dispatch", zxCjDispatch);
    }

    public Integer getZxCjDispatch() {
        return get("zx_cj_dispatch");
    }


    public void setInsuranceOverdraftAmount(java.math.BigDecimal insuranceOverdraftAmount) {
        set("insurance_overdraft_amount", insuranceOverdraftAmount);
    }

    public java.math.BigDecimal getInsuranceOverdraftAmount() {
        return get("insurance_overdraft_amount");
    }

    public void setTixianAmount(java.lang.Integer tixianAmount) {
        set("tixian_amount", tixianAmount);
    }

    public java.lang.Integer getTixianAmount() {
        return get("tixian_amount");
    }


    public void setDispatchMillDefault(String dispatchMillDefault) {
        set("dispatch_mill_default", dispatchMillDefault);
    }

    public Double getDispatchMillDefault() {
        return get("dispatch_mill_default");
    }


    public void setGrabSingleMillDefault(String grabSingleMillDefault) {
        set("grab_single_default", grabSingleMillDefault);
    }

    public Double getGrabSingleMillDefault() {
        return get("grab_single_default");
    }


    public void setAdditionalCharges(java.math.BigDecimal additionalCharges) {
        set("additional_charges", additionalCharges);
    }

    public java.math.BigDecimal getAdditionalCharges() {
        return get("additional_charges");
    }


    public java.lang.Double getUCarChargeRate() {
        return get("u_car_charge_rate");
    }

    public void setUCarChargeRate(java.lang.Double uCarChargeRate) {
        set("u_car_charge_rate", uCarChargeRate);
    }

    public void setDriverCancelTime(java.lang.Integer driverCancelTime) {
        set("driver_cancel_time", driverCancelTime);
    }

    public java.lang.Integer getDriverCancelTime() {
        return get("driver_cancel_time");
    }

    public void setMemberCancelTime(java.lang.Integer memberCancelTime) {
        set("member_cancel_time", memberCancelTime);
    }

    public java.lang.Integer getMemberCancelTime() {
        return get("member_cancel_time");
    }


}
