package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSpecialCar<M extends BaseSpecialCar<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCompanyId(Integer companyId) {
		set("company_id", companyId);
	}

	public Integer getCompanyId() {
		return get("company_id");
	}

	public void setSetoutTime1(java.util.Date setoutTime1) {
		set("setout_time1", setoutTime1);
	}

	public java.util.Date getSetoutTime1() {
		return get("setout_time1");
	}

	public void setSetoutTime2(java.util.Date setoutTime2) {
		set("setout_time2", setoutTime2);
	}

	public java.util.Date getSetoutTime2() {
		return get("setout_time2");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setNeedTime(String needTime) {
		set("need_time", needTime);
	}

	public Double getNeedTime() {
		return get("need_time");
	}

	public void setDistance(Double distance) {
		set("distance", distance);
	}

	public Double getDistance() {
		return get("distance");
	}

	public void setEndAdcode(String endAdcode) {
		set("end_adcode", endAdcode);
	}

	public String getEndAdcode() {
		return get("end_adcode");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setPeople(Integer people) {
		set("people", people);
	}

	public Integer getPeople() {
		return get("people");
	}

	public void setRecordType(Integer recordType) {
		set("record_type", recordType);
	}

	public Integer getRecordType() {
		return get("record_type");
	}

	public void setStartLongitude(Double startLongitude) {
		set("start_longitude", startLongitude);
	}

	public Double getStartLongitude() {
		return get("start_longitude");
	}

	public void setStartLatitude(Double startLatitude) {
		set("start_latitude", startLatitude);
	}

	public Double getStartLatitude() {
		return get("start_latitude");
	}

	public void setEndLongitude(Double endLongitude) {
		set("end_longitude", endLongitude);
	}

	public Double getEndLongitude() {
		return get("end_longitude");
	}

	public void setEndLatitude(Double endLatitude) {
		set("end_latitude", endLatitude);
	}

	public Double getEndLatitude() {
		return get("end_latitude");
	}

	public void setEstimatedPrice(java.math.BigDecimal estimatedPrice) {
		set("estimated_price", estimatedPrice);
	}

	public java.math.BigDecimal getEstimatedPrice() {
		return get("estimated_price");
	}

	public void setSharingEsyimatedPrice(java.math.BigDecimal sharingEsyimatedPrice) {
		set("sharing_esyimated_price", sharingEsyimatedPrice);
	}

	public java.math.BigDecimal getSharingEsyimatedPrice() {
		return get("sharing_esyimated_price");
	}

	public void setIndexPrice(java.math.BigDecimal indexPrice) {
		set("index_price", indexPrice);
	}

	public java.math.BigDecimal getIndexPrice() {
		return get("index_price");
	}

	public void setSharingPrice(java.math.BigDecimal sharingPrice) {
		set("sharing_price", sharingPrice);
	}

	public java.math.BigDecimal getSharingPrice() {
		return get("sharing_price");
	}

	public void setStartAdcode(String startAdcode) {
		set("start_adcode", startAdcode);
	}

	public String getStartAdcode() {
		return get("start_adcode");
	}

	public void setFlag(Boolean flag) {
		set("flag", flag);
	}

	public Boolean getFlag() {
		return get("flag");
	}

	public void setTag(String tag) {
		set("tag", tag);
	}

	public String getTag() {
		return get("tag");
	}

	public void setReservationAddress(String reservationAddress) {
		set("reservationAddress", reservationAddress);
	}

	public String getReservationAddress() {
		return get("reservationAddress");
	}

	public void setDestination(String destination) {
		set("destination", destination);
	}

	public String getDestination() {
		return get("destination");
	}

	public void setReservationCity(String reservationCity) {
		set("reservationCity", reservationCity);
	}

	public String getReservationCity() {
		return get("reservationCity");
	}

	public void setDestinationCity(String destinationCity) {
		set("destinationCity", destinationCity);
	}

	public String getDestinationCity() {
		return get("destinationCity");
	}

}
