package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberActivity<M extends BaseMemberActivity<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return get("id");
    }

    public void setLoginId(Integer loginId) {
        set("login_id", loginId);
    }

    public Integer getLoginId() {
        return get("login_id");
    }

    public void setActivityId(Integer activityId) {
        set("activity_id", activityId);
    }

    public Integer getActivityId() {
        return get("activity_id");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setAppType(Integer appType) {
        set("app_type", appType);
    }

    public Integer getAppType() {
        return get("app_type");
    }

}
