package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJoin<M extends BaseJoin<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setUserName(String userName) {
		set("user_name", userName);
	}

	public String getUserName() {
		return get("user_name");
	}

	public void setRealName(String realName) {
		set("real_name", realName);
	}

	public String getRealName() {
		return get("real_name");
	}

	public void setAddr(String addr) {
		set("addr", addr);
	}

	public String getAddr() {
		return get("addr");
	}

	public void setSex(Boolean sex) {
		set("sex", sex);
	}

	public Boolean getSex() {
		return get("sex");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setHeadPortrait(String headPortrait) {
		set("head_portrait", headPortrait);
	}

	public String getHeadPortrait() {
		return get("head_portrait");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setAge(Integer age) {
		set("age", age);
	}

	public Integer getAge() {
		return get("age");
	}

	public void setPhono(String phono) {
		set("phono", phono);
	}

	public String getPhono() {
		return get("phono");
	}

}
