package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChargeStandardItem<M extends BaseChargeStandardItem<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setBaseAmount(java.math.BigDecimal baseAmount) {
		set("base_amount", baseAmount);
	}

	public java.math.BigDecimal getBaseAmount() {
		return get("base_amount");
	}

	public void setCreater(Integer creater) {
		set("creater", creater);
	}

	public Integer getCreater() {
		return get("creater");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setChaoguogonglishu(java.math.BigDecimal chaoguogonglishu) {
		set("chaoguogonglishu", chaoguogonglishu);
	}

	public java.math.BigDecimal getChaoguogonglishu() {
		return get("chaoguogonglishu");
	}

	public void setMeiduoshaogongli(java.math.BigDecimal meiduoshaogongli) {
		set("meiduoshaogongli", meiduoshaogongli);
	}

	public java.math.BigDecimal getMeiduoshaogongli() {
		return get("meiduoshaogongli");
	}

	public void setBuzugonglishu(java.math.BigDecimal buzugonglishu) {
		set("buzugonglishu", buzugonglishu);
	}

	public java.math.BigDecimal getBuzugonglishu() {
		return get("buzugonglishu");
	}

	public void setGonglijiashoujine(java.math.BigDecimal gonglijiashoujine) {
		set("gonglijiashoujine", gonglijiashoujine);
	}

	public java.math.BigDecimal getGonglijiashoujine() {
		return get("gonglijiashoujine");
	}

	public void setQibufenzhong(java.math.BigDecimal qibufenzhong) {
		set("qibufenzhong", qibufenzhong);
	}

	public java.math.BigDecimal getQibufenzhong() {
		return get("qibufenzhong");
	}

	public void setMeiduoshaofengzhong(java.math.BigDecimal meiduoshaofengzhong) {
		set("meiduoshaofengzhong", meiduoshaofengzhong);
	}

	public java.math.BigDecimal getMeiduoshaofengzhong() {
		return get("meiduoshaofengzhong");
	}

	public void setBuzufengzhong(java.math.BigDecimal buzufengzhong) {
		set("buzufengzhong", buzufengzhong);
	}

	public java.math.BigDecimal getBuzufengzhong() {
		return get("buzufengzhong");
	}

	public void setFengzhongjiashoujine(java.math.BigDecimal fengzhongjiashoujine) {
		set("fengzhongjiashoujine", fengzhongjiashoujine);
	}

	public java.math.BigDecimal getFengzhongjiashoujine() {
		return get("fengzhongjiashoujine");
	}

	public void setMianfeidenghoufenzhong(java.math.BigDecimal mianfeidenghoufenzhong) {
		set("mianfeidenghoufenzhong", mianfeidenghoufenzhong);
	}

	public java.math.BigDecimal getMianfeidenghoufenzhong() {
		return get("mianfeidenghoufenzhong");
	}

	public void setDenghouchaoguolijijiashoujine(java.math.BigDecimal denghouchaoguolijijiashoujine) {
		set("denghouchaoguolijijiashoujine", denghouchaoguolijijiashoujine);
	}

	public java.math.BigDecimal getDenghouchaoguolijijiashoujine() {
		return get("denghouchaoguolijijiashoujine");
	}

	public void setDenghouchaoguojiashoujine(java.math.BigDecimal denghouchaoguojiashoujine) {
		set("denghouchaoguojiashoujine", denghouchaoguojiashoujine);
	}

	public java.math.BigDecimal getDenghouchaoguojiashoujine() {
		return get("denghouchaoguojiashoujine");
	}

	public void setDenghoudiyuduoshaofenzhong(java.math.BigDecimal denghoudiyuduoshaofenzhong) {
		set("denghoudiyuduoshaofenzhong", denghoudiyuduoshaofenzhong);
	}

	public java.math.BigDecimal getDenghoudiyuduoshaofenzhong() {
		return get("denghoudiyuduoshaofenzhong");
	}

	public void setDenghoumeiduoshaofengzhong(java.math.BigDecimal denghoumeiduoshaofengzhong) {
		set("denghoumeiduoshaofengzhong", denghoumeiduoshaofengzhong);
	}

	public java.math.BigDecimal getDenghoumeiduoshaofengzhong() {
		return get("denghoumeiduoshaofengzhong");
	}

	public void setChargeStandard(Integer chargeStandard) {
		set("charge_standard", chargeStandard);
	}

	public Integer getChargeStandard() {
		return get("charge_standard");
	}

	public void setMinAmount(java.math.BigDecimal minAmount) {
		set("min_amount", minAmount);
	}

	public java.math.BigDecimal getMinAmount() {
		return get("min_amount");
	}

	public void setOneDiscount1(java.math.BigDecimal oneDiscount1) {
		set("one_discount1", oneDiscount1);
	}

	public java.math.BigDecimal getOneDiscount1() {
		return get("one_discount1");
	}

	public void setOneDiscount2(java.math.BigDecimal oneDiscount2) {
		set("one_discount2", oneDiscount2);
	}

	public java.math.BigDecimal getOneDiscount2() {
		return get("one_discount2");
	}

	public void setOneDiscount3(java.math.BigDecimal oneDiscount3) {
		set("one_discount3", oneDiscount3);
	}

	public java.math.BigDecimal getOneDiscount3() {
		return get("one_discount3");
	}

	public void setOneDiscount4(java.math.BigDecimal oneDiscount4) {
		set("one_discount4", oneDiscount4);
	}

	public java.math.BigDecimal getOneDiscount4() {
		return get("one_discount4");
	}

	public void setOneDiscount5(java.math.BigDecimal oneDiscount5) {
		set("one_discount5", oneDiscount5);
	}

	public java.math.BigDecimal getOneDiscount5() {
		return get("one_discount5");
	}

	public void setOneDistance1(Integer oneDistance1) {
		set("one_distance1", oneDistance1);
	}

	public Integer getOneDistance1() {
		return get("one_distance1");
	}

	public void setOneDistance2(Integer oneDistance2) {
		set("one_distance2", oneDistance2);
	}

	public Integer getOneDistance2() {
		return get("one_distance2");
	}

	public void setOneDistance3(Integer oneDistance3) {
		set("one_distance3", oneDistance3);
	}

	public Integer getOneDistance3() {
		return get("one_distance3");
	}

	public void setOneDistance4(Integer oneDistance4) {
		set("one_distance4", oneDistance4);
	}

	public Integer getOneDistance4() {
		return get("one_distance4");
	}

	public void setOneDistance5(Integer oneDistance5) {
		set("one_distance5", oneDistance5);
	}

	public Integer getOneDistance5() {
		return get("one_distance5");
	}

	public void setTwoDiscount1(java.math.BigDecimal twoDiscount1) {
		set("two_discount1", twoDiscount1);
	}

	public java.math.BigDecimal getTwoDiscount1() {
		return get("two_discount1");
	}

	public void setTwoDiscount2(java.math.BigDecimal twoDiscount2) {
		set("two_discount2", twoDiscount2);
	}

	public java.math.BigDecimal getTwoDiscount2() {
		return get("two_discount2");
	}

	public void setTwoDiscount3(java.math.BigDecimal twoDiscount3) {
		set("two_discount3", twoDiscount3);
	}

	public java.math.BigDecimal getTwoDiscount3() {
		return get("two_discount3");
	}

	public void setTwoDiscount4(java.math.BigDecimal twoDiscount4) {
		set("two_discount4", twoDiscount4);
	}

	public java.math.BigDecimal getTwoDiscount4() {
		return get("two_discount4");
	}

	public void setTwoDiscount5(java.math.BigDecimal twoDiscount5) {
		set("two_discount5", twoDiscount5);
	}

	public java.math.BigDecimal getTwoDiscount5() {
		return get("two_discount5");
	}

	public void setTwoDistance1(Integer twoDistance1) {
		set("two_distance1", twoDistance1);
	}

	public Integer getTwoDistance1() {
		return get("two_distance1");
	}

	public void setTwoDistance2(Integer twoDistance2) {
		set("two_distance2", twoDistance2);
	}

	public Integer getTwoDistance2() {
		return get("two_distance2");
	}

	public void setTwoDistance3(Integer twoDistance3) {
		set("two_distance3", twoDistance3);
	}

	public Integer getTwoDistance3() {
		return get("two_distance3");
	}

	public void setTwoDistance4(Integer twoDistance4) {
		set("two_distance4", twoDistance4);
	}

	public Integer getTwoDistance4() {
		return get("two_distance4");
	}

	public void setTwoDistance5(Integer twoDistance5) {
		set("two_distance5", twoDistance5);
	}

	public Integer getTwoDistance5() {
		return get("two_distance5");
	}

	public void setThreeDiscount1(java.math.BigDecimal threeDiscount1) {
		set("three_discount1", threeDiscount1);
	}

	public java.math.BigDecimal getThreeDiscount1() {
		return get("three_discount1");
	}

	public void setThreeDiscount2(java.math.BigDecimal threeDiscount2) {
		set("three_discount2", threeDiscount2);
	}

	public java.math.BigDecimal getThreeDiscount2() {
		return get("three_discount2");
	}

	public void setThreeDiscount3(java.math.BigDecimal threeDiscount3) {
		set("three_discount3", threeDiscount3);
	}

	public java.math.BigDecimal getThreeDiscount3() {
		return get("three_discount3");
	}

	public void setThreeDiscount4(java.math.BigDecimal threeDiscount4) {
		set("three_discount4", threeDiscount4);
	}

	public java.math.BigDecimal getThreeDiscount4() {
		return get("three_discount4");
	}

	public void setThreeDiscount5(java.math.BigDecimal threeDiscount5) {
		set("three_discount5", threeDiscount5);
	}

	public java.math.BigDecimal getThreeDiscount5() {
		return get("three_discount5");
	}

	public void setThreeDistance1(Integer threeDistance1) {
		set("three_distance1", threeDistance1);
	}

	public Integer getThreeDistance1() {
		return get("three_distance1");
	}

	public void setThreeDistance2(Integer threeDistance2) {
		set("three_distance2", threeDistance2);
	}

	public Integer getThreeDistance2() {
		return get("three_distance2");
	}

	public void setThreeDistance3(Integer threeDistance3) {
		set("three_distance3", threeDistance3);
	}

	public Integer getThreeDistance3() {
		return get("three_distance3");
	}

	public void setThreeDistance4(Integer threeDistance4) {
		set("three_distance4", threeDistance4);
	}

	public Integer getThreeDistance4() {
		return get("three_distance4");
	}

	public void setThreeDistance5(Integer threeDistance5) {
		set("three_distance5", threeDistance5);
	}

	public Integer getThreeDistance5() {
		return get("three_distance5");
	}

}
