package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserJoin<M extends BaseUserJoin<M>> extends Model<M> implements IBean {

	public void setUser(Integer user) {
		set("user", user);
	}

	public Integer getUser() {
		return get("user");
	}

	public void setJoin(Integer join) {
		set("join", join);
	}

	public Integer getJoin() {
		return get("join");
	}

}
