package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverCredit<M extends BaseDriverCredit<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setDriverId(Integer driverId) {
		set("driver_id", driverId);
	}

	public Integer getDriverId() {
		return get("driver_id");
	}

	public void setLever(Integer Lever) {
		set("Lever", Lever);
	}

	public Integer getLever() {
		return get("Lever");
	}

	public void setTestDate(java.util.Date TestDate) {
		set("TestDate", TestDate);
	}

	public java.util.Date getTestDate() {
		return get("TestDate");
	}

	public void setTestDepartment(String TestDepartment) {
		set("TestDepartment", TestDepartment);
	}

	public String getTestDepartment() {
		return get("TestDepartment");
	}

}
