package base.models;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberLogin<M extends BaseMemberLogin<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return get("id");
    }

    public void setUserName(String userName) {
        set("user_name", userName);
    }

    public String getUserName() {
        return get("user_name");
    }

    public void setPassword(String password) {
        set("password", password);
    }

    public String getPassword() {
        return get("password");
    }

    public void setSalt(String salt) {
        set("salt", salt);
    }

    public String getSalt() {
        return get("salt");
    }

    public void setType(Integer type) {
        set("type", type);
    }

    public Integer getType() {
        return get("type");
    }

    public void setDeviceNo(String deviceNo) {
        set("device_no", deviceNo);
    }

    public String getDeviceNo() {
        return get("device_no");
    }

    public void setLastLoginTime(java.util.Date lastLoginTime) {
        set("last_login_time", lastLoginTime);
    }

    public java.util.Date getLastLoginTime() {
        return get("last_login_time");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getStatus() {
        return get("status");
    }

    public void setDeviceType(Integer deviceType) {
        set("device_type", deviceType);
    }

    public Integer getDeviceType() {
        return get("device_type");
    }

    public void setCacheKey(String cacheKey) {
        set("cache_key", cacheKey);
    }

    public String getCacheKey() {
        return get("cache_key");
    }

    public void setLastUpdateTime(java.util.Date lastUpdateTime) {
        set("last_update_time", lastUpdateTime);
    }

    public java.util.Date getLastUpdateTime() {
        return get("last_update_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setServiceType(Integer serviceType) {
        set("service_type", serviceType);
    }

    public Integer getServiceType() {
        return get("service_type");
    }

    public void setRegistrationId(String registrationId) {
        set("registration_id", registrationId);
    }

    public String getRegistrationId() {
        return get("registration_id");
    }

    public void setLoginStatus(Integer loginStatus) {
        set("login_status", loginStatus);
    }

    public Integer getLoginStatus() {
        return get("login_status");
    }

    public void setIp(String ip) {
        set("ip", ip);
    }

    public String getIp() {
        return get("ip");
    }

    public void setLandingIp(java.lang.String landingIp) {
        set("landing_ip", landingIp);
    }

    public java.lang.String getLandingIp() {
        return get("landing_ip");
    }

    public void setLandingImsi(java.lang.String landingImsi) {
        set("landing_IMSI", landingImsi);
    }

    public java.lang.String getLandingImsi() {
        return get("landing_IMSI");
    }

    public void setLandingImei(java.lang.String landingImei) {
        set("landing_IMEI", landingImei);
    }

    public java.lang.String getLandingImei() {
        return get("landing_IMEI");
    }

    public void setLandingLongitude(java.lang.Double landingLongitude) {
        set("landing_longitude", landingLongitude);
    }

    public java.lang.Double getLandingLongitude() {
        return get("landing_longitude");
    }

    public void setLandingLatitude(java.lang.Double landingLatitude) {
        set("landing_latitude", landingLatitude);
    }

    public java.lang.Double getLandingLatitude() {
        return get("landing_latitude");
    }

    public void setIdentifying(java.lang.String identifying) {
        set("identifying", identifying);
    }

    public java.lang.String getIdentifying() {
        return get("identifying");
    }

    public void setMacAddress(java.lang.String macAddress) {
        set("mac_address", macAddress);
    }

    public java.lang.String getMacAddress() {
        return get("mac_address");
    }

    public void setPort(java.lang.String port) {
        set("port", port);
    }

    public java.lang.String getPort() {
        return get("port");
    }
}
