package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverApp<M extends BaseDriverApp<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setNetType(Integer NetType) {
		set("NetType", NetType);
	}

	public Integer getNetType() {
		return get("NetType");
	}

	public void setAppVersion(String AppVersion) {
		set("AppVersion", AppVersion);
	}

	public String getAppVersion() {
		return get("AppVersion");
	}

	public void setMapType(Integer MapType) {
		set("MapType", MapType);
	}

	public Integer getMapType() {
		return get("MapType");
	}

	public void setState(Integer State) {
		set("State", State);
	}

	public Integer getState() {
		return get("State");
	}

	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}

	public Integer getFlag() {
		return get("Flag");
	}

	public void setUpdateTime(java.util.Date UpdateTime) {
		set("UpdateTime", UpdateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UpdateTime");
	}

	public void setDriverId(Integer driverId) {
		set("driver_id", driverId);
	}

	public Integer getDriverId() {
		return get("driver_id");
	}

}
