package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyService<M extends BaseCompanyService<M>> extends Model<M> implements IBean {
    
    public void setId(Integer id) {
        set("id", id);
    }
    
    public Integer getId() {
        return get("id");
    }
    
    public void setCompany(Integer company) {
        set("company", company);
    }
    
    public Integer getCompany() {
        return get("company");
    }
    
    public void setServiceTypeItem(Integer serviceTypeItem) {
        set("service_type_item", serviceTypeItem);
    }
    
    public Integer getServiceTypeItem() {
        return get("service_type_item");
    }
    
    public void setChargeStandard(Integer chargeStandard) {
        set("charge_standard", chargeStandard);
    }
    
    public Integer getChargeStandard() {
        return get("charge_standard");
    }
    
    public void setRoyaltyStandard(Integer royaltyStandard) {
        set("royalty_standard", royaltyStandard);
    }
    
    public Integer getRoyaltyStandard() {
        return get("royalty_standard");
    }
    
    public void setRoyaltyStandardForCreate(Integer royaltyStandardForCreate) {
        set("royalty_standard_forcreate", royaltyStandardForCreate);
    }
    
    public Integer getRoyaltyStandardForCreate() {
        return get("royalty_standard_forcreate");
    }
    
    public void setLastUpdateTime(java.util.Date lastUpdateTime) {
        set("last_update_time", lastUpdateTime);
    }
    
    public java.util.Date getLastUpdateTime() {
        return get("last_update_time");
    }
    
    
    public void setStatus(Integer Status) {
        set("status", Status);
    }
    
    public Integer getStatus() {
        return get("status");
    }
    
}
