package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistributionSetting<M extends BaseDistributionSetting<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreater(Integer creater) {
		set("creater", creater);
	}

	public Integer getCreater() {
		return get("creater");
	}

	public void setStyle(Integer style) {
		set("style", style);
	}

	public Integer getStyle() {
		return get("style");
	}

	public void setFirstLevel(java.math.BigDecimal firstLevel) {
		set("first_level", firstLevel);
	}

	public java.math.BigDecimal getFirstLevel() {
		return get("first_level");
	}

	public void setThirdLevel(java.math.BigDecimal thirdLevel) {
		set("third_level", thirdLevel);
	}

	public java.math.BigDecimal getThirdLevel() {
		return get("third_level");
	}

	public void setSecondLevel(java.math.BigDecimal secondLevel) {
		set("second_level", secondLevel);
	}

	public java.math.BigDecimal getSecondLevel() {
		return get("second_level");
	}

	public void setOrderCount(Integer orderCount) {
		set("order_count", orderCount);
	}

	public Integer getOrderCount() {
		return get("order_count");
	}

	public void setDescribe(String describe) {
		set("describe", describe);
	}

	public String getDescribe() {
		return get("describe");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}

	public Integer getLevel() {
		return get("level");
	}

	public void setFirstType(Integer firstType) {
		set("first_type", firstType);
	}

	public Integer getFirstType() {
		return get("first_type");
	}

	public void setSecondType(Integer secondType) {
		set("second_type", secondType);
	}

	public Integer getSecondType() {
		return get("second_type");
	}

	public void setThirdType(Integer thirdType) {
		set("third_type", thirdType);
	}

	public Integer getThirdType() {
		return get("third_type");
	}

	public void setServiceType(Integer ServiceType) {
		set("service_type", ServiceType);
	}

	public Integer getServiceType() {
		return get("service_type");
	}
}
