package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverInfo<M extends BaseDriverInfo<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setLoginId(Integer loginId) {
		set("login_id", loginId);
	}

	public Integer getLoginId() {
		return get("login_id");
	}

	public void setNickName(String nickName) {
		set("nick_name", nickName);
	}

	public String getNickName() {
		return get("nick_name");
	}

	public void setHeadPortrait(String headPortrait) {
		set("head_portrait", headPortrait);
	}

	public String getHeadPortrait() {
		return get("head_portrait");
	}

	public void setRealName(String realName) {
		set("real_name", realName);
	}

	public String getRealName() {
		return get("real_name");
	}

	public void setProvince(String province) {
		set("province", province);
	}

	public String getProvince() {
		return get("province");
	}

	public void setCity(String city) {
		set("city", city);
	}

	public String getCity() {
		return get("city");
	}

	public void setCounty(String county) {
		set("county", county);
	}

	public String getCounty() {
		return get("county");
	}

	public void setCertificateType(Integer certificateType) {
		set("certificate_type", certificateType);
	}

	public Integer getCertificateType() {
		return get("certificate_type");
	}

	public void setCertificateNo(String certificateNo) {
		set("certificate_no", certificateNo);
	}

	public String getCertificateNo() {
		return get("certificate_no");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setPostCode(String postCode) {
		set("post_code", postCode);
	}

	public String getPostCode() {
		return get("post_code");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("last_update_time", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("last_update_time");
	}

	public void setGender(Integer gender) {
		set("gender", gender);
	}

	public Integer getGender() {
		return get("gender");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return get("type");
	}

	public void setJobType(Integer jobType) {
		set("job_type", jobType);
	}

	public Integer getJobType() {
		return get("job_type");
	}

	public void setFromType(Integer fromType) {
		set("from_type", fromType);
	}

	public Integer getFromType() {
		return get("from_type");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setIntroducerLoginId(Integer introducerLoginId) {
		set("introducer_login_id", introducerLoginId);
	}

	public Integer getIntroducerLoginId() {
		return get("introducer_login_id");
	}

	public void setLevel(Integer level) {
		set("level", level);
	}

	public Integer getLevel() {
		return get("level");
	}

	public void setOnlineTime(Integer onlineTime) {
		set("online_time", onlineTime);
	}

	public Integer getOnlineTime() {
		return get("online_time");
	}

	public void setCreater(Integer creater) {
		set("creater", creater);
	}

	public Integer getCreater() {
		return get("creater");
	}

	public void setTexiRe(Integer texiRe) {
		set("texi_re", texiRe);
	}

	public Integer getTexiRe() {
		return get("texi_re");
	}

	public void setDjRe(Integer djRe) {
		set("dj_re", djRe);
	}

	public Integer getDjRe() {
		return get("dj_re");
	}

	public void setZcSushiRe(Integer zcSushiRe) {
		set("zc_sushi_re", zcSushiRe);
	}

	public Integer getZcSushiRe() {
		return get("zc_sushi_re");
	}

	public void setZcHaohuaRe(Integer zcHaohuaRe) {
		set("zc_haohua_re", zcHaohuaRe);
	}

	public Integer getZcHaohuaRe() {
		return get("zc_haohua_re");
	}

	public void setZcShangwuRe(Integer zcShangwuRe) {
		set("zc_shangwu_re", zcShangwuRe);
	}

	public Integer getZcShangwuRe() {
		return get("zc_shangwu_re");
	}

	public void setHkzhuanxianRe(Integer hkzhuanxianRe) {
		set("hkzhuanxian_re", hkzhuanxianRe);
	}

	public Integer getHkzhuanxianRe() {
		return get("hkzhuanxian_re");
	}

	public void setKcRe(Integer kcRe) {
		set("kc_re", kcRe);
	}

	public Integer getKcRe() {
		return get("kc_re");
	}

	public void setTxPassword(String txPassword) {
		set("tx_password", txPassword);
	}

	public String getTxPassword() {
		return get("tx_password");
	}

	public void setShunfengcheRe(Integer shunfengcheRe) {
		set("shunfengche_re", shunfengcheRe);
	}

	public Integer getShunfengcheRe() {
		return get("shunfengche_re");
	}

	public void setZhuanxianRe(Integer zhuanxianRe) {
		set("zhuanxian_re", zhuanxianRe);
	}

	public Integer getZhuanxianRe() {
		return get("zhuanxian_re");
	}

	public void setLicenseId(String LicenseId) {
		set("LicenseId", LicenseId);
	}

	public String getLicenseId() {
		return get("LicenseId");
	}

	public void setDriverNation(String DriverNation) {
		set("DriverNation", DriverNation);
	}

	public String getDriverNation() {
		return get("DriverNation");
	}

	public void setGetDriverLicenseDate(java.util.Date GetDriverLicenseDate) {
		set("GetDriverLicenseDate", GetDriverLicenseDate);
	}

	public java.util.Date getGetDriverLicenseDate() {
		return get("GetDriverLicenseDate");
	}

	public void setDriverLicenseOn(java.util.Date DriverLicenseOn) {
		set("DriverLicenseOn", DriverLicenseOn);
	}

	public java.util.Date getDriverLicenseOn() {
		return get("DriverLicenseOn");
	}

	public void setDriverLicenseOff(java.util.Date DriverLicenseOff) {
		set("DriverLicenseOff", DriverLicenseOff);
	}

	public java.util.Date getDriverLicenseOff() {
		return get("DriverLicenseOff");
	}

	public void setTaxiDriver(Integer TaxiDriver) {
		set("TaxiDriver", TaxiDriver);
	}

	public Integer getTaxiDriver() {
		return get("TaxiDriver");
	}

	public void setCertificateNo2(String CertificateNo2) {
		set("CertificateNo2", CertificateNo2);
	}

	public String getCertificateNo2() {
		return get("CertificateNo2");
	}

	public void setNetworkCarIssueOrganization(String NetworkCarIssueOrganization) {
		set("NetworkCarIssueOrganization", NetworkCarIssueOrganization);
	}

	public String getNetworkCarIssueOrganization() {
		return get("NetworkCarIssueOrganization");
	}

	public void setNetworkCarIssueDate(java.util.Date NetworkCarIssueDate) {
		set("NetworkCarIssueDate", NetworkCarIssueDate);
	}

	public java.util.Date getNetworkCarIssueDate() {
		return get("NetworkCarIssueDate");
	}

	public void setGetNetworkCarProofDate(java.util.Date GetNetworkCarProofDate) {
		set("GetNetworkCarProofDate", GetNetworkCarProofDate);
	}

	public java.util.Date getGetNetworkCarProofDate() {
		return get("GetNetworkCarProofDate");
	}

	public void setNetworkCarProofOn(java.util.Date NetworkCarProofOn) {
		set("NetworkCarProofOn", NetworkCarProofOn);
	}

	public java.util.Date getNetworkCarProofOn() {
		return get("NetworkCarProofOn");
	}

	public void setNetworkCarProofOff(java.util.Date NetworkCarProofOff) {
		set("NetworkCarProofOff", NetworkCarProofOff);
	}

	public java.util.Date getNetworkCarProofOff() {
		return get("NetworkCarProofOff");
	}

	public void setRegisterDate(java.util.Date RegisterDate) {
		set("RegisterDate", RegisterDate);
	}

	public java.util.Date getRegisterDate() {
		return get("RegisterDate");
	}

	public void setCommercialType(Integer CommercialType) {
		set("CommercialType", CommercialType);
	}

	public Integer getCommercialType() {
		return get("CommercialType");
	}

	public void setContractCompany(String ContractCompany) {
		set("ContractCompany", ContractCompany);
	}

	public String getContractCompany() {
		return get("ContractCompany");
	}

	public void setContractOn(java.util.Date ContractOn) {
		set("ContractOn", ContractOn);
	}

	public java.util.Date getContractOn() {
		return get("ContractOn");
	}

	public void setContractOff(java.util.Date ContractOff) {
		set("ContractOff", ContractOff);
	}

	public java.util.Date getContractOff() {
		return get("ContractOff");
	}

	public void setAllow(Integer Allow) {
		set("Allow", Allow);
	}

	public Integer getAllow() {
		return get("Allow");
	}

	public void setAllow2(Integer Allow2) {
		set("Allow2", Allow2);
	}

	public Integer getAllow2() {
		return get("Allow2");
	}

	public void setDriverLicenseId(String DriverLicenseId) {
		set("DriverLicenseId", DriverLicenseId);
	}

	public String getDriverLicenseId() {
		return get("DriverLicenseId");
	}

	public void setInDriverBlacklist(Integer InDriverBlacklist) {
		set("InDriverBlacklist", InDriverBlacklist);
	}

	public Integer getInDriverBlacklist() {
		return get("InDriverBlacklist");
	}

	public void setDriverNationAlity(String DriverNationAlity) {
		set("DriverNationAlity", DriverNationAlity);
	}

	public String getDriverNationAlity() {
		return get("DriverNationAlity");
	}

	public void setDriverMaritalStatus(String DriverMaritalStatus) {
		set("DriverMaritalStatus", DriverMaritalStatus);
	}

	public String getDriverMaritalStatus() {
		return get("DriverMaritalStatus");
	}

	public void setDriverLanguageLevel(String DriverLanguageLevel) {
		set("DriverLanguageLevel", DriverLanguageLevel);
	}

	public String getDriverLanguageLevel() {
		return get("DriverLanguageLevel");
	}

	public void setDriverEducation(String DriverEducation) {
		set("DriverEducation", DriverEducation);
	}

	public String getDriverEducation() {
		return get("DriverEducation");
	}

	public void setDriverCensus(String DriverCensus) {
		set("DriverCensus", DriverCensus);
	}

	public String getDriverCensus() {
		return get("DriverCensus");
	}

	public void setDriverAddress(String DriverAddress) {
		set("DriverAddress", DriverAddress);
	}

	public String getDriverAddress() {
		return get("DriverAddress");
	}

	public void setDriverContactAddress(String DriverContactAddress) {
		set("DriverContactAddress", DriverContactAddress);
	}

	public String getDriverContactAddress() {
		return get("DriverContactAddress");
	}

	public void setDriverType(String DriverType) {
		set("DriverType", DriverType);
	}

	public String getDriverType() {
		return get("DriverType");
	}

	public void setEmergencyContact(String EmergencyContact) {
		set("EmergencyContact", EmergencyContact);
	}

	public String getEmergencyContact() {
		return get("EmergencyContact");
	}

	public void setEmergencyContactPhone(String EmergencyContactPhone) {
		set("EmergencyContactPhone", EmergencyContactPhone);
	}

	public String getEmergencyContactPhone() {
		return get("EmergencyContactPhone");
	}

	public void setEmergencyContactAddress(String EmergencyContactAddress) {
		set("EmergencyContactAddress", EmergencyContactAddress);
	}

	public String getEmergencyContactAddress() {
		return get("EmergencyContactAddress");
	}

	public void setState(Integer State) {
		set("State", State);
	}

	public Integer getState() {
		return get("State");
	}

	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}

	public Integer getFlag() {
		return get("Flag");
	}

	public void setRegisterIp(String registerIp) {
		set("register_ip", registerIp);
	}

	public String getRegisterIp() {
		return get("register_ip");
	}

	public void setRegisterImsi(String registerImsi) {
		set("register_IMSI", registerImsi);
	}

	public String getRegisterImsi() {
		return get("register_IMSI");
	}

	public void setRegisterImei(String registerImei) {
		set("register_IMEI", registerImei);
	}

	public String getRegisterImei() {
		return get("register_IMEI");
	}

	public void setIdentifying(String identifying) {
		set("identifying", identifying);
	}

	public String getIdentifying() {
		return get("identifying");
	}

	public void setMacAddress(String macAddress) {
		set("mac_address", macAddress);
	}

	public String getMacAddress() {
		return get("mac_address");
	}

	public void setPort(String port) {
		set("port", port);
	}

	public String getPort() {
		return get("port");
	}

}
