package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVersion<M extends BaseVersion<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return get("id");
    }

    public void setVersionNo(java.lang.String versionNo) {
        set("version_no", versionNo);
    }

    public java.lang.String getVersionNo() {
        return get("version_no");
    }

    public void setVersion(java.lang.Integer version) {
        set("version", version);
    }

    public java.lang.Integer getVersion() {
        return get("version");
    }

    public void setFilePath(java.lang.String filePath) {
        set("file_path", filePath);
    }

    public java.lang.String getFilePath() {
        return get("file_path");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("update_time", updateTime);
    }

    public java.util.Date getUpdateTime() {
        return get("update_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setType(java.lang.Integer type) {
        set("type", type);
    }

    public java.lang.Integer getType() {
        return get("type");
    }

    public void setDescription(java.lang.String description) {
        set("description", description);
    }

    public java.lang.String getDescription() {
        return get("description");
    }

    public void setQcode(java.lang.String qcode) {
        set("qcode", qcode);
    }

    public java.lang.String getQcode() {
        return get("qcode");
    }

    public void setOsType(java.lang.Integer osType) {
        set("os_type", osType);
    }

    public java.lang.Integer getOsType() {
        return get("os_type");
    }

    public void setForce(java.lang.Integer force) {
        set("force", force);
    }

    public java.lang.Integer getForce() {
        return get("force");
    }

    public void setCrc(java.lang.String crc) {
        set("crc", crc);
    }

    public java.lang.String getCrc() {
        return get("crc");
    }

    public void setHvalue(java.lang.String hvalue) {
        set("hvalue", hvalue);
    }

    public java.lang.String getHvalue() {
        return get("hvalue");
    }

}
