package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverLicenseInfo<M extends BaseDriverLicenseInfo<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return get("id");
    }

    public void setDriver(Integer driver) {
        set("driver", driver);
    }

    public Integer getDriver() {
        return get("driver");
    }

    public void setDriverLicense(String driverLicense) {
        set("driver_license", driverLicense);
    }

    public String getDriverLicense() {
        return get("driver_license");
    }

    public void setDrivingLicense(String drivingLicense) {
        set("driving_license", drivingLicense);
    }

    public String getDrivingLicense() {
        return get("driving_license");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getStatus() {
        return get("status");
    }

    public void setPhoto(String photo) {
        set("photo", photo);
    }

    public String getPhoto() {
        return get("photo");
    }

    public void setIdCard(String idCard) {
        set("id_card", idCard);
    }

    public String getIdCard() {
        return get("id_card");
    }

    public void setQualificationCertificate(java.lang.String qualificationCertificate) {
        set("qualification_certificate", qualificationCertificate);
    }

    public java.lang.String getQualificationCertificate() {
        return get("qualification_certificate");
    }
}
