package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWechatpayLog<M extends BaseWechatpayLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setReturnCode(String returnCode) {
		set("return_code", returnCode);
	}

	public String getReturnCode() {
		return get("return_code");
	}

	public void setReturnMsg(String returnMsg) {
		set("return_msg", returnMsg);
	}

	public String getReturnMsg() {
		return get("return_msg");
	}

	public void setAppid(String appid) {
		set("appid", appid);
	}

	public String getAppid() {
		return get("appid");
	}

	public void setMchId(String mchId) {
		set("mch_id", mchId);
	}

	public String getMchId() {
		return get("mch_id");
	}

	public void setDeviceInfo(String deviceInfo) {
		set("device_info", deviceInfo);
	}

	public String getDeviceInfo() {
		return get("device_info");
	}

	public void setNonceStr(String nonceStr) {
		set("nonce_str", nonceStr);
	}

	public String getNonceStr() {
		return get("nonce_str");
	}

	public void setSign(String sign) {
		set("sign", sign);
	}

	public String getSign() {
		return get("sign");
	}

	public void setSignType(String signType) {
		set("sign_type", signType);
	}

	public String getSignType() {
		return get("sign_type");
	}

	public void setResultCode(String resultCode) {
		set("result_code", resultCode);
	}

	public String getResultCode() {
		return get("result_code");
	}

	public void setErrCode(String errCode) {
		set("err_code", errCode);
	}

	public String getErrCode() {
		return get("err_code");
	}

	public void setErrCodeDes(String errCodeDes) {
		set("err_code_des", errCodeDes);
	}

	public String getErrCodeDes() {
		return get("err_code_des");
	}

	public void setOpenid(String openid) {
		set("openid", openid);
	}

	public String getOpenid() {
		return get("openid");
	}

	public void setIsSubscribe(String isSubscribe) {
		set("is_subscribe", isSubscribe);
	}

	public String getIsSubscribe() {
		return get("is_subscribe");
	}

	public void setTradeType(String tradeType) {
		set("trade_type", tradeType);
	}

	public String getTradeType() {
		return get("trade_type");
	}

	public void setBankType(String bankType) {
		set("bank_type", bankType);
	}

	public String getBankType() {
		return get("bank_type");
	}

	public void setTotalFee(String totalFee) {
		set("total_fee", totalFee);
	}

	public String getTotalFee() {
		return get("total_fee");
	}

	public void setSettlementTotalFee(Integer settlementTotalFee) {
		set("settlement_total_fee", settlementTotalFee);
	}

	public String getSettlementTotalFee() {
		return get("settlement_total_fee");
	}

	public void setFeeType(String feeType) {
		set("fee_type", feeType);
	}

	public String getFeeType() {
		return get("fee_type");
	}

	public void setCashFee(String cashFee) {
		set("cash_fee", cashFee);
	}

	public String getCashFee() {
		return get("cash_fee");
	}

	public void setCashFeeType(String cashFeeType) {
		set("cash_fee_type", cashFeeType);
	}

	public String getCashFeeType() {
		return get("cash_fee_type");
	}

	public void setTransactionId(String transactionId) {
		set("transaction_id", transactionId);
	}

	public String getTransactionId() {
		return get("transaction_id");
	}

	public void setOutTradeNo(String outTradeNo) {
		set("out_trade_no", outTradeNo);
	}

	public String getOutTradeNo() {
		return get("out_trade_no");
	}

	public void setAttach(String attach) {
		set("attach", attach);
	}

	public String getAttach() {
		return get("attach");
	}

	public void setTimeEnd(String timeEnd) {
		set("time_end", timeEnd);
	}

	public String getTimeEnd() {
		return get("time_end");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
