package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyAccountLog<M extends BaseCompanyAccountLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setOpeartType(Integer opeartType) {
		set("opeart_type", opeartType);
	}

	public Integer getOpeartType() {
		return get("opeart_type");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setOpearter(Integer opearter) {
		set("opearter", opearter);
	}

	public Integer getOpearter() {
		return get("opearter");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setServiceType(Integer id) {
		set("service_type", id);
	}

	public Integer getServiceType() {
		return get("service_type");
	}

}
