package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrip<M extends BaseTrip<M>> extends Model<M> implements IBean {

	public void setOrderId(Integer orderId) {
		set("order_id", orderId);
	}

	public Integer getOrderId() {
		return get("order_id");
	}

	public void setMember(Integer member) {
		set("member", member);
	}

	public Integer getMember() {
		return get("member");
	}

	public void setStartLongitude(Double startLongitude) {
		set("start_longitude", startLongitude);
	}

	public Double getStartLongitude() {
		return get("start_longitude");
	}

	public void setStartLatitude(Double startLatitude) {
		set("start_latitude", startLatitude);
	}

	public Double getStartLatitude() {
		return get("start_latitude");
	}

	public void setEndLongitude(Double endLongitude) {
		set("end_longitude", endLongitude);
	}

	public Double getEndLongitude() {
		return get("end_longitude");
	}

	public void setEndLatitude(Double endLatitude) {
		set("end_latitude", endLatitude);
	}

	public Double getEndLatitude() {
		return get("end_latitude");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

}
