package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseCar<M extends BaseBaseCar<M>> extends Model<M> implements IBean {
    
    public void setId(java.lang.Integer id) {
        set("id", id);
    }
    
    public java.lang.Integer getId() {
        return get("id");
    }
    
    public void setPlateNo(java.lang.String plateNo) {
        set("plate_no", plateNo);
    }
    
    public java.lang.String getPlateNo() {
        return get("plate_no");
    }
    
    public void setVin(java.lang.String vin) {
        set("vin", vin);
    }
    
    public java.lang.String getVin() {
        return get("vin");
    }
    
    public void setPicture(java.lang.String picture) {
        set("picture", picture);
    }
    
    public java.lang.String getPicture() {
        return get("picture");
    }
    
    public void setColor(java.lang.String color) {
        set("color", color);
    }
    
    public java.lang.String getColor() {
        return get("color");
    }
    
    public void setType(java.lang.Integer type) {
        set("type", type);
    }
    
    public java.lang.Integer getType() {
        return get("type");
    }
    
    public void setPlateColor(java.lang.String plateColor) {
        set("plate_color", plateColor);
    }
    
    public java.lang.String getPlateColor() {
        return get("plate_color");
    }
    
    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }
    
    public java.util.Date getCreateTime() {
        return get("create_time");
    }
    
    public void setBrand(java.lang.Integer brand) {
        set("brand", brand);
    }
    
    public java.lang.Integer getBrand() {
        return get("brand");
    }
    
    public void setModelType(java.lang.Integer modelType) {
        set("model_type", modelType);
    }
    
    public java.lang.Integer getModelType() {
        return get("model_type");
    }
    
    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }
    
    public java.lang.Integer getStatus() {
        return get("status");
    }
    
    public void setSeats(java.lang.String Seats) {
        set("Seats", Seats);
    }
    
    public java.lang.String getSeats() {
        return get("Seats");
    }
    
    public void setOwnerName(java.lang.String OwnerName) {
        set("OwnerName", OwnerName);
    }
    
    public java.lang.String getOwnerName() {
        return get("OwnerName");
    }
    
    public void setEngineId(java.lang.String EngineId) {
        set("EngineId", EngineId);
    }
    
    public java.lang.String getEngineId() {
        return get("EngineId");
    }
    
    public void setFuelType(java.lang.String FuelType) {
        set("FuelType", FuelType);
    }
    
    public java.lang.String getFuelType() {
        return get("FuelType");
    }
    
    public void setEngineDisplace(java.lang.String EngineDisplace) {
        set("EngineDisplace", EngineDisplace);
    }
    
    public java.lang.String getEngineDisplace() {
        return get("EngineDisplace");
    }
    
    public void setTransAgency(java.lang.String TransAgency) {
        set("TransAgency", TransAgency);
    }
    
    public java.lang.String getTransAgency() {
        return get("TransAgency");
    }
    
    public void setTransArea(java.lang.String TransArea) {
        set("TransArea", TransArea);
    }
    
    public java.lang.String getTransArea() {
        return get("TransArea");
    }
    
    public void setTransDateStart(java.util.Date TransDateStart) {
        set("TransDateStart", TransDateStart);
    }
    
    public java.util.Date getTransDateStart() {
        return get("TransDateStart");
    }
    
    public void setTransDateStop(java.util.Date TransDateStop) {
        set("TransDateStop", TransDateStop);
    }
    
    public java.util.Date getTransDateStop() {
        return get("TransDateStop");
    }
    
    public void setCertifyDateB(java.util.Date CertifyDateB) {
        set("CertifyDateB", CertifyDateB);
    }
    
    public java.util.Date getCertifyDateB() {
        return get("CertifyDateB");
    }
    
    public void setFixState(java.lang.Integer FixState) {
        set("FixState", FixState);
    }
    
    public java.lang.Integer getFixState() {
        return get("FixState");
    }
    
    public void setCheckState(java.lang.Integer CheckState) {
        set("CheckState", CheckState);
    }
    
    public java.lang.Integer getCheckState() {
        return get("CheckState");
    }
    
    public void setFeePrintId(java.lang.String FeePrintId) {
        set("FeePrintId", FeePrintId);
    }
    
    public java.lang.String getFeePrintId() {
        return get("FeePrintId");
    }
    
    public void setGPSBrand(java.lang.String GPSBrand) {
        set("GPSBrand", GPSBrand);
    }
    
    public java.lang.String getGPSBrand() {
        return get("GPSBrand");
    }
    
    public void setGPSModel(java.lang.String GPSModel) {
        set("GPSModel", GPSModel);
    }
    
    public java.lang.String getGPSModel() {
        return get("GPSModel");
    }
    
    public void setGPSinstallDate(java.util.Date GPSinstallDate) {
        set("GPSinstallDate", GPSinstallDate);
    }
    
    public java.util.Date getGPSinstallDate() {
        return get("GPSinstallDate");
    }
    
    public void setRegisterDate(java.util.Date RegisterDate) {
        set("RegisterDate", RegisterDate);
    }
    
    public java.util.Date getRegisterDate() {
        return get("RegisterDate");
    }
    
    public void setCertifyDateA(java.util.Date CertifyDateA) {
        set("CertifyDateA", CertifyDateA);
    }
    
    public java.util.Date getCertifyDateA() {
        return get("CertifyDateA");
    }
    
    public void setCommercialType(java.lang.Integer CommercialType) {
        set("CommercialType", CommercialType);
    }
    
    public java.lang.Integer getCommercialType() {
        return get("CommercialType");
    }
    
    public void setUpdateTime(java.util.Date UpdateTime) {
        set("UpdateTime", UpdateTime);
    }
    
    public java.util.Date getUpdateTime() {
        return get("UpdateTime");
    }
    
    public void setCertificate(java.lang.String Certificate) {
        set("Certificate", Certificate);
    }
    
    public java.lang.String getCertificate() {
        return get("Certificate");
    }
    
    public void setNextFixDate(java.lang.Integer NextFixDate) {
        set("NextFixDate", NextFixDate);
    }
    
    public java.lang.Integer getNextFixDate() {
        return get("NextFixDate");
    }
    
    public void setGPSIMEI(java.lang.String GPSIMEI) {
        set("GPSIMEI", GPSIMEI);
    }
    
    public java.lang.String getGPSIMEI() {
        return get("GPSIMEI");
    }
    
    public void setFareType(java.lang.String FareType) {
        set("FareType", FareType);
    }
    
    public java.lang.String getFareType() {
        return get("FareType");
    }
    
    public void setState(java.lang.Integer State) {
        set("State", State);
    }
    
    public java.lang.Integer getState() {
        return get("State");
    }
    
    public void setFlag(java.lang.Integer Flag) {
        set("Flag", Flag);
    }
    
    public java.lang.Integer getFlag() {
        return get("Flag");
    }
    
    public void setVehicleType(java.lang.String VehicleType) {
        set("VehicleType", VehicleType);
    }
    
    public java.lang.String getVehicleType() {
        return get("VehicleType");
    }
    
}
