package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBank<M extends BaseBank<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setBankBin(String bankBin) {
		set("bank_bin", bankBin);
	}

	public String getBankBin() {
		return get("bank_bin");
	}

	public void setBankName(String bankName) {
		set("bank_name", bankName);
	}

	public String getBankName() {
		return get("bank_name");
	}

}
