package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyPermit<M extends BaseCompanyPermit<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setAddress(String Address) {
		set("Address", Address);
	}

	public String getAddress() {
		return get("Address");
	}

	public void setCertificate(String Certificate) {
		set("Certificate", Certificate);
	}

	public String getCertificate() {
		return get("Certificate");
	}

	public void setOperationArea(String OperationArea) {
		set("OperationArea", OperationArea);
	}

	public String getOperationArea() {
		return get("OperationArea");
	}

	public void setOwnerName(String OwnerName) {
		set("OwnerName", OwnerName);
	}

	public String getOwnerName() {
		return get("OwnerName");
	}

	public void setStartDate(java.util.Date StartDate) {
		set("StartDate", StartDate);
	}

	public java.util.Date getStartDate() {
		return get("StartDate");
	}

	public void setStopDate(java.util.Date StopDate) {
		set("StopDate", StopDate);
	}

	public java.util.Date getStopDate() {
		return get("StopDate");
	}

	public void setCertifyDate(java.util.Date CertifyDate) {
		set("CertifyDate", CertifyDate);
	}

	public java.util.Date getCertifyDate() {
		return get("CertifyDate");
	}

	public void setState(String State) {
		set("State", State);
	}

	public String getState() {
		return get("State");
	}

	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}

	public Integer getFlag() {
		return get("Flag");
	}

	public void setUpdateTime(java.util.Date UpdateTime) {
		set("UpdateTime", UpdateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UpdateTime");
	}

}
