package base.models;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberInfo<M extends BaseMemberInfo<M>> extends Model<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return get("id");
    }

    public void setLoginId(Integer loginId) {
        set("login_id", loginId);
    }

    public Integer getLoginId() {
        return get("login_id");
    }

    public void setNickName(String nickName) {
        set("nick_name", nickName);
    }

    public String getNickName() {
        return get("nick_name");
    }

    public void setHeadPortrait(String headPortrait) {
        set("head_portrait", headPortrait);
    }

    public String getHeadPortrait() {
        return get("head_portrait");
    }

    public void setAge(Integer age) {
        set("age", age);
    }

    public Integer getAge() {
        return get("age");
    }

    public void setBirthday(java.util.Date birthday) {
        set("birthday", birthday);
    }

    public java.util.Date getBirthday() {
        return get("birthday");
    }

    public void setPhone(String phone) {
        set("phone", phone);
    }

    public String getPhone() {
        return get("phone");
    }

    public void setProvince(String province) {
        set("province", province);
    }

    public String getProvince() {
        return get("province");
    }

    public void setCity(String city) {
        set("city", city);
    }

    public String getCity() {
        return get("city");
    }

    public void setCounty(String county) {
        set("county", county);
    }

    public String getCounty() {
        return get("county");
    }

    public void setAddress(String address) {
        set("address", address);
    }

    public String getAddress() {
        return get("address");
    }

    public void setEmail(String email) {
        set("email", email);
    }

    public String getEmail() {
        return get("email");
    }

    public void setRealName(String realName) {
        set("real_name", realName);
    }

    public String getRealName() {
        return get("real_name");
    }

    public void setCertificateType(Integer certificateType) {
        set("certificate_type", certificateType);
    }

    public Integer getCertificateType() {
        return get("certificate_type");
    }

    public void setCertificateNo(String certificateNo) {
        set("certificate_no", certificateNo);
    }

    public String getCertificateNo() {
        return get("certificate_no");
    }

    public void setGender(Integer gender) {
        set("gender", gender);
    }

    public Integer getGender() {
        return get("gender");
    }

    public void setUrgentPhone(String urgentPhone) {
        set("urgent_phone", urgentPhone);
    }

    public String getUrgentPhone() {
        return get("urgent_phone");
    }

    public void setUrgentName(String urgentName) {
        set("urgent_name", urgentName);
    }

    public String getUrgentName() {
        return get("urgent_name");
    }

    public void setLevel(Integer level) {
        set("level", level);
    }

    public Integer getLevel() {
        return get("level");
    }

    public void setLastUpdateTime(java.util.Date lastUpdateTime) {
        set("last_update_time", lastUpdateTime);
    }

    public java.util.Date getLastUpdateTime() {
        return get("last_update_time");
    }

    public void setPostCode(String postCode) {
        set("post_code", postCode);
    }

    public String getPostCode() {
        return get("post_code");
    }

    public void setCompany(Integer company) {
        set("company", company);
    }

    public Integer getCompany() {
        return get("company");
    }

    public void setFromType(Integer fromType) {
        set("from_type", fromType);
    }

    public Integer getFromType() {
        return get("from_type");
    }

    public void setChargeStandard(Integer chargeStandard) {
        set("charge_standard", chargeStandard);
    }

    public Integer getChargeStandard() {
        return get("charge_standard");
    }

    public void setIntroducerLoginId(Integer introducerLoginId) {
        set("introducer_login_id", introducerLoginId);
    }

    public Integer getIntroducerLoginId() {
        return get("introducer_login_id");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getStatus() {
        return get("status");
    }

    public void setCreater(Integer creater) {
        set("creater", creater);
    }

    public Integer getCreater() {
        return get("creater");
    }

    public void setTxPassword(String txPassword) {
        set("tx_password", txPassword);
    }

    public String getTxPassword() {
        return get("tx_password");
    }

    public void setRegisterIp(java.lang.String registerIp) {
        set("register_ip", registerIp);
    }

    public java.lang.String getRegisterIp() {
        return get("register_ip");
    }

    public void setRegisterImsi(java.lang.String registerImsi) {
        set("register_IMSI", registerImsi);
    }

    public java.lang.String getRegisterImsi() {
        return get("register_IMSI");
    }

    public void setRegisterImei(java.lang.String registerImei) {
        set("register_IMEI", registerImei);
    }

    public java.lang.String getRegisterImei() {
        return get("register_IMEI");
    }

    public void setIdentifying(java.lang.String identifying) {
        set("identifying", identifying);
    }

    public java.lang.String getIdentifying() {
        return get("identifying");
    }

    public void setMacAddress(java.lang.String macAddress) {
        set("mac_address", macAddress);
    }

    public java.lang.String getMacAddress() {
        return get("mac_address");
    }

    public void setPort(java.lang.String port) {
        set("port", port);
    }

    public java.lang.String getPort() {
        return get("port");
    }
}
