package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSpeciallineOrder<M extends BaseSpeciallineOrder<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setOrderId(Integer orderId) {
		set("orderId", orderId);
	}

	public Integer getOrderId() {
		return get("orderId");
	}

	public void setSpecialcarId(Integer specialcarId) {
		set("specialcarId", specialcarId);
	}

	public Integer getSpecialcarId() {
		return get("specialcarId");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
