package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxLine<M extends BaseZxLine<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCompanyId(Integer companyId) {
		set("company_id", companyId);
	}

	public Integer getCompanyId() {
		return get("company_id");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setStartLongitude(Double startLongitude) {
		set("start_longitude", startLongitude);
	}

	public Double getStartLongitude() {
		return get("start_longitude");
	}

	public void setStartLatitude(Double startLatitude) {
		set("start_latitude", startLatitude);
	}

	public Double getStartLatitude() {
		return get("start_latitude");
	}

	public void setEndLongitude(Double endLongitude) {
		set("end_longitude", endLongitude);
	}

	public Double getEndLongitude() {
		return get("end_longitude");
	}

	public void setEndLatitude(Double endLatitude) {
		set("end_latitude", endLatitude);
	}

	public Double getEndLatitude() {
		return get("end_latitude");
	}

	public void setReservationCity(String reservationCity) {
		set("reservationCity", reservationCity);
	}

	public String getReservationCity() {
		return get("reservationCity");
	}

	public void setStartAddressDetail(String startAddressDetail) {
		set("start_address_detail", startAddressDetail);
	}

	public String getStartAddressDetail() {
		return get("start_address_detail");
	}

	public void setDestinationCity(String destinationCity) {
		set("destinationCity", destinationCity);
	}

	public String getDestinationCity() {
		return get("destinationCity");
	}

	public void setEndAddressDetail(String endAddressDetail) {
		set("end_address_detail", endAddressDetail);
	}

	public String getEndAddressDetail() {
		return get("end_address_detail");
	}

	public void setDistance(Double distance) {
		set("distance", distance);
	}

	public Double getDistance() {
		return get("distance");
	}

	public void setDelFlag(Integer delFlag) {
		set("del_flag", delFlag);
	}

	public Integer getDelFlag() {
		return get("del_flag");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setPriceSpecial(java.math.BigDecimal priceSpecial) {
		set("price_special", priceSpecial);
	}

	public java.math.BigDecimal getPriceSpecial() {
		return get("price_special");
	}

	public void setSharingPrice(java.math.BigDecimal sharingPrice) {
		set("sharing_price", sharingPrice);
	}

	public java.math.BigDecimal getSharingPrice() {
		return get("sharing_price");
	}

	public void setSharingPriceSpecial(java.math.BigDecimal sharingPriceSpecial) {
		set("sharing_price_special", sharingPriceSpecial);
	}

	public java.math.BigDecimal getSharingPriceSpecial() {
		return get("sharing_price_special");
	}

	public void setStartProvince(String startProvince) {
		set("start_province", startProvince);
	}

	public String getStartProvince() {
		return get("start_province");
	}

	public void setStartCounty(String startCounty) {
		set("start_county", startCounty);
	}

	public String getStartCounty() {
		return get("start_county");
	}

	public void setStartCity(String startCity) {
		set("start_city", startCity);
	}

	public String getStartCity() {
		return get("start_city");
	}

	public void setStartCode(String startCode) {
		set("start_code", startCode);
	}

	public String getStartCode() {
		return get("start_code");
	}

	public void setEndProvince(String endProvince) {
		set("end_province", endProvince);
	}

	public String getEndProvince() {
		return get("end_province");
	}

	public void setEndCounty(String endCounty) {
		set("end_county", endCounty);
	}

	public String getEndCounty() {
		return get("end_county");
	}

	public void setEndCity(String endCity) {
		set("end_city", endCity);
	}

	public String getEndCity() {
		return get("end_city");
	}

	public void setEndCode(String endCode) {
		set("end_code", endCode);
	}

	public String getEndCode() {
		return get("end_code");
	}

	public void setSetoutTime1(java.util.Date setoutTime1) {
		set("setout_time1", setoutTime1);
	}

	public java.util.Date getSetoutTime1() {
		return get("setout_time1");
	}

	public void setSetoutTime2(java.util.Date setoutTime2) {
		set("setout_time2", setoutTime2);
	}

	public java.util.Date getSetoutTime2() {
		return get("setout_time2");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
