package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return get("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setSalt(String salt) {
		set("salt", salt);
	}

	public String getSalt() {
		return get("salt");
	}

	public void setDefaultFlag(Boolean defaultFlag) {
		set("default_flag", defaultFlag);
	}

	public Boolean getDefaultFlag() {
		return get("default_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setSuperAdmin(Boolean superAdmin) {
		set("super_admin", superAdmin);
	}

	public Boolean getSuperAdmin() {
		return get("super_admin");
	}

	public void setGender(Integer gender) {
		set("gender", gender);
	}

	public Integer getGender() {
		return get("gender");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setQq(String qq) {
		set("qq", qq);
	}

	public String getQq() {
		return get("qq");
	}

	public void setWxchat(String wxchat) {
		set("wxchat", wxchat);
	}

	public String getWxchat() {
		return get("wxchat");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setLastLoginIp(String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}

	public String getLastLoginIp() {
		return get("last_login_ip");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setHeadPortrait(String headPortrait) {
		set("head_portrait", headPortrait);
	}

	public String getHeadPortrait() {
		return get("head_portrait");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setRole(Integer role) {
		set("role", role);
	}

	public Integer getRole() {
		return get("role");
	}

	public void setLoginId(Integer loginId) {
		set("login_id", loginId);
	}

	public Integer getLoginId() {
		return get("login_id");
	}

}
