package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuditLog<M extends BaseAuditLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setAuditer(Integer auditer) {
		set("auditer", auditer);
	}

	public Integer getAuditer() {
		return get("auditer");
	}

	public void setCompany(Integer company) {
		set("company", company);
	}

	public Integer getCompany() {
		return get("company");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("audit_time", auditTime);
	}

	public java.util.Date getAuditTime() {
		return get("audit_time");
	}

	public void setAuditRemark(String auditRemark) {
		set("audit_remark", auditRemark);
	}

	public String getAuditRemark() {
		return get("audit_remark");
	}

	public void setOkFlag(Boolean okFlag) {
		set("ok_flag", okFlag);
	}

	public Boolean getOkFlag() {
		return get("ok_flag");
	}

	public void setLicense(Integer license) {
		set("license", license);
	}

	public Integer getLicense() {
		return get("license");
	}

}
