package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriverCar<M extends BaseDriverCar<M>> extends Model<M> implements IBean {

	public void setDriver(Integer driver) {
		set("driver", driver);
	}

	public Integer getDriver() {
		return get("driver");
	}

	public void setCar(Integer car) {
		set("car", car);
	}

	public Integer getCar() {
		return get("car");
	}

	public void setUseFlag(Boolean useFlag) {
		set("use_flag", useFlag);
	}

	public Boolean getUseFlag() {
		return get("use_flag");
	}

}
