package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyPay<M extends BaseCompanyPay<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setPayName(String PayName) {
		set("PayName", PayName);
	}

	public String getPayName() {
		return get("PayName");
	}

	public void setPayId(String PayId) {
		set("PayId", PayId);
	}

	public String getPayId() {
		return get("PayId");
	}

	public void setPayType(String PayType) {
		set("PayType", PayType);
	}

	public String getPayType() {
		return get("PayType");
	}

	public void setPayScope(String PayScope) {
		set("PayScope", PayScope);
	}

	public String getPayScope() {
		return get("PayScope");
	}

	public void setPrepareBank(String PrepareBank) {
		set("PrepareBank", PrepareBank);
	}

	public String getPrepareBank() {
		return get("PrepareBank");
	}

	public void setCountDate(Integer CountDate) {
		set("CountDate", CountDate);
	}

	public Integer getCountDate() {
		return get("CountDate");
	}

	public void setState(Integer State) {
		set("State", State);
	}

	public Integer getState() {
		return get("State");
	}

	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}

	public Integer getFlag() {
		return get("Flag");
	}

	public void setUpdateTime(java.util.Date UpdateTime) {
		set("UpdateTime", UpdateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("UpdateTime");
	}

}
