package base.models;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppSetting<M extends BaseAppSetting<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setDriverAppkey(String driverAppkey) {
		set("driver_appkey", driverAppkey);
	}

	public String getDriverAppkey() {
		return get("driver_appkey");
	}

	public void setDriverSecret(String driverSecret) {
		set("driver_secret", driverSecret);
	}

	public String getDriverSecret() {
		return get("driver_secret");
	}

	public void setCustomerAppkey(String customerAppkey) {
		set("customer_appkey", customerAppkey);
	}

	public String getCustomerAppkey() {
		return get("customer_appkey");
	}

	public void setCustomerSecret(String customerSecret) {
		set("customer_secret", customerSecret);
	}

	public String getCustomerSecret() {
		return get("customer_secret");
	}

	public void setAliAppId(String aliAppId) {
		set("ali_app_id", aliAppId);
	}

	public String getAliAppId() {
		return get("ali_app_id");
	}

	public void setAliPid(String aliPid) {
		set("ali_pid", aliPid);
	}

	public String getAliPid() {
		return get("ali_pid");
	}

	public void setAliTargetId(String aliTargetId) {
		set("ali_target_id", aliTargetId);
	}

	public String getAliTargetId() {
		return get("ali_target_id");
	}

	public void setAliNotifyUrl(String aliNotifyUrl) {
		set("ali_notify_url", aliNotifyUrl);
	}

	public String getAliNotifyUrl() {
		return get("ali_notify_url");
	}

	public void setAliRsaPrivate(String aliRsaPrivate) {
		set("ali_rsa_private", aliRsaPrivate);
	}

	public String getAliRsaPrivate() {
		return get("ali_rsa_private");
	}

	public void setLastUpdate(java.util.Date lastUpdate) {
		set("last_update", lastUpdate);
	}

	public java.util.Date getLastUpdate() {
		return get("last_update");
	}

	public void setLastOperater(Integer lastOperater) {
		set("last_operater", lastOperater);
	}

	public Integer getLastOperater() {
		return get("last_operater");
	}

}
