package base.models;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberAppraise<M extends BaseMemberAppraise<M>> extends Model<M> implements IBean {

    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }

    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    public String getCompanyId() {
        return get("CompanyId");
    }

    public void setOrderId(String OrderId) {
        set("OrderId", OrderId);
    }

    public String getOrderId() {
        return get("OrderId");
    }

    public void setEvaluateTime(Long EvaluateTime) {
        set("EvaluateTime", EvaluateTime);
    }

    public Long getEvaluateTime() {
        return get("EvaluateTime");
    }

    public void setServiceScore(Integer ServiceScore) {
        set("ServiceScore", ServiceScore);
    }

    public Integer getServiceScore() {
        return get("ServiceScore");
    }

    public void setDriverScore(Integer DriverScore) {
        set("DriverScore", DriverScore);
    }

    public Integer getDriverScore() {
        return get("DriverScore");
    }

    public void setVehicleScore(Integer VehicleScore) {
        set("VehicleScore", VehicleScore);
    }

    public Integer getVehicleScore() {
        return get("VehicleScore");
    }

    public void setDetail(String Detail) {
        set("Detail", Detail);
    }

    public String getDetail() {
        return get("Detail");
    }


}
