package models.vip;

import annotation.TableBind;
import base.models.BaseVipInfo;
import plugin.sqlInXml.SqlManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "vip_info")
public class VipInfo extends BaseVipInfo<VipInfo> {
    public static final VipInfo dao = new VipInfo();
    
    public VipInfo findByLoginId(int loginId) {
        return findFirst(SqlManager.sql("vipInfo.findByLoginId"), loginId);
    }
}
