package models.portModels;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("A10", "id", A10.class);
		arp.addMapping("A12", "id", A12.class);
		arp.addMapping("A14", "id", A14.class);
		arp.addMapping("A16", "id", A16.class);
		arp.addMapping("A18", "id", A18.class);
		arp.addMapping("A20", "id", A20.class);
		arp.addMapping("A22", "id", A22.class);
		arp.addMapping("A24", "id", A24.class);
		arp.addMapping("A26", "id", A26.class);
		arp.addMapping("A28", "id", A28.class);
		arp.addMapping("A30", "id", A30.class);
		arp.addMapping("A32", "id", A32.class);
		arp.addMapping("A34", "id", A34.class);
		arp.addMapping("A36", "id", A36.class);
		arp.addMapping("A38", "id", A38.class);
		arp.addMapping("A4", "id", A4.class);
		arp.addMapping("A40", "id", A40.class);
		arp.addMapping("A42", "id", A42.class);
		arp.addMapping("A44", "id", A44.class);
		arp.addMapping("A46", "id", A46.class);
		arp.addMapping("A48", "id", A48.class);
		arp.addMapping("A50", "id", A50.class);
		arp.addMapping("A52", "id", A52.class);
		arp.addMapping("A54", "id", A54.class);
		arp.addMapping("A56", "id", A56.class);
		arp.addMapping("A58", "id", A58.class);
		arp.addMapping("A6", "id", A6.class);
		arp.addMapping("A60", "id", A60.class);
		arp.addMapping("A62", "id", A62.class);
		arp.addMapping("A64", "id", A64.class);
		arp.addMapping("A66", "id", A66.class);
		arp.addMapping("A8", "id", A8.class);
	}
}

