package models.portModels;

import annotation.TableBind;
import base.portModels.BaseA12;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A12")
public class A12 extends BaseA12<A12> {
	public static final A12 dao = new A12();
	public List<A12> findCompany(){
		return  find("Select * from A12");
	}
}
