package models.portModels;

import annotation.TableBind;
import base.portModels.BaseA14;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A14")
public class A14 extends BaseA14<A14> {
	public static final A14 dao = new A14();
	public List<A14> findCompany(){
		return  find("Select * from A14");
	}
}
