package models.portModels;


import utils.DateUtil;
import annotation.TableBind;
import base.Constant;
import base.portModels.BaseA18;
import models.car.Insurance;

import java.util.List;

/**
 * Generated by JFinal.
 */

@TableBind(tableName = "A18")
public class A18 extends BaseA18<A18> {
	public static final A18 dao = new A18();
	public List<A18> findCompany(){
		return  find("Select * from A18");
	}

	public void setInfos() {
		List<Insurance> list = Insurance.dao.findInfos();
		for (Insurance  insurance: list) {
			try {
				A18 a18 = new A18();
				a18.setVehicleNo(insurance.getVehicleNo());
				a18.setInsurCom(insurance.getInsurCom());
				a18.setInsurNum(insurance.getInsurNum());
				a18.setInsurType(insurance.getInsurType());
				a18.setInsurCount(insurance.getInsurCount());
				a18.setInsurEff(insurance.getInsurEff());
				a18.setInsurExp(insurance.getInsurExp());
				a18.setFlag(Constant.Flag.ADD);
				a18.setUpdateTime(DateUtil.UpdateTime());
				a18.save();
			}catch (Exception e){
				System.out.println("车牌号码："+insurance.getVehicleNo()+"插入A18错误");
				continue;
			}

		}

	}

}
