package models.portModels;


import utils.DateUtil;
import annotation.TableBind;
import base.Constant;
import base.portModels.BaseA20;
import models.car.CarInfo;
import java.util.List;

/**
 * Generated by JFinal.
 */

@TableBind(tableName = "A20")
public class A20 extends BaseA20<A20> {
	public static final A20 dao = new A20();
	public List<A20>findCompany(){
		return  find("Select * from A20");
	}


	public void setInfos(){
		List<CarInfo> carInfos = CarInfo.dao.findCarDistance();
		for (int i = 0;i<carInfos.size();i++){
			CarInfo carInfo = carInfos.get(i);
			A20 a20 = new A20();
			try {
				a20.setVehicleNo((String) carInfo.get("VehicleNo"));
				a20.setTotalMile((Long) carInfo.get("TotalMile"));
				a20.setFlag(Constant.Flag.ADD);
				a20.setUpdateTime(DateUtil.UpdateTime());
				a20.save();
			}catch (Exception e){
				System.out.println("车辆公里数:"+carInfo.get("VehicleNo")+" 插入表A20失败");
			}
		}
	}

}
