package models.portModels;


import utils.DateUtil;
import annotation.TableBind;
import base.Constant;
import base.portModels.BaseA24;
import models.driver.DriverInfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A24")
public class A24 extends BaseA24<A24> {
	public static final A24 dao = new A24();
	public List<A24> findCompany(){
		return  find("Select * from A24");
	}


	public void setInfos(){
		List<DriverInfo> list = DriverInfo.dao.driverInfos();
		for (DriverInfo driverInfo : list){
			try {
				A24 A24 = new A24();
				A24.setLicenseId((String) driverInfo.get("LicenseId"));
				A24.setCourseName("机动车驾驶培训教学与考试大纲");
				A24.setCourseDate(20170620);
				A24.setStartTime("20170620");
				A24.setStopTime("20170621");
				A24.setDuration((long) 2);
				A24.setFlag(Constant.Flag.ADD);
				A24.setUpdateTime(DateUtil.UpdateTime());
				A24.save();
			}catch (NullPointerException e){
				System.out.println("手机号码："+driverInfo.get("DriverPhone")+"插入A24错误");
				continue;
			}
		}
	}

}
