package models.portModels;


import utils.DateUtil;
import annotation.TableBind;
import base.Constant;
import base.portModels.BaseA26;
import models.driver.DriverInfo;

import java.util.Arrays;
import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A26")
public class A26 extends BaseA26<A26> {
	public static final A26 dao = new A26();
	public List<A26> findCompany(){
		return  find("Select * from A26");
	}

	public void setInfos(){
		List<DriverInfo> list = DriverInfo.dao.driverInfoPhone();
		int[] ChinaUnicom = {130, 131,132,155,156,186,185,176};
		int[] ChinaTelecom = {134,135,136,137,138,139,150,151,152,157,158,159,182,183,184,188,187,147,178};
		int[] ChinaMobile = {133,153,180,181,189,177};
		for (int i = 0;i<list.size();i++){
			DriverInfo driverInfo = list.get(i);
			try {
				A26 A26 = new A26();
				String Phone = driverInfo.get("DriverPhone");
				A26.setLicenseId((String) driverInfo.get("LicenseId"));
				A26.setDriverPhone(Phone);
//				A26.setAppVersion((String) driverInfo.get("AppVersion"));
//				A26.setLicenseId("34012119747071335");
//				A26.setDriverPhone("18655059138");
				A26.setAppVersion("3.3.71");
				A26.setMapType(Constant.MapType.GAODE);
				A26.setState(0);
				A26.setFlag(Constant.Flag.ADD);
				A26.setUpdateTime(DateUtil.UpdateTime());
				int i1 = Integer.parseInt(Phone.substring(0,3));
				int i2 = Arrays.binarySearch(ChinaUnicom,i1);
				if (Arrays.binarySearch(ChinaUnicom,i1) >= 0){
					A26.setNetType(1);
				}else if (Arrays.binarySearch(ChinaMobile,i1) >= 0){
					A26.setNetType(3);
				}else if (Arrays.binarySearch(ChinaTelecom,i1) >= 0){
					A26.setNetType(2);
				}else {
					A26.setNetType(4);
				}
				A26.save();
			}catch (NullPointerException e){
				System.out.println("手机号码："+driverInfo.get("DriverPhone")+"插入A26错误");
				continue;
			}
		}
	}

}
