package models.portModels;

import annotation.TableBind;
import base.portModels.BaseA4;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A4")
public class A4 extends BaseA4<A4> {
	public static final A4 dao = new A4();

	public List<A4> findCompany(){
		return  find("Select * from A4");
	}
}
