package models.portModels;


import annotation.TableBind;
import base.portModels.BaseA54;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A54")
public class A54 extends BaseA54<A54> {
    public static final A54 dao = new A54();

    public List<A54> findCompany() {
        return find("Select * from A54");
    }

    /**
     * 添加数据
     */
    public void add() {


        List<A32> list1 = A32.dao.findCompany();
        for (int i = 120; i <= 220; i++) {
            try {
                A54 a54 = new A54();
                a54.setOrderId(list1.get(i).getOrderId());//订单号
                a54.setComplaintTime(list1.get(i).getDepartTime() + 010000);//投诉时间


                if (i % 5 == 0) {
                    a54.setDetail("司机拒接");//投诉内容
                    a54.setResult("处罚20元");//处理结果
                } else {
                    a54.setDetail("司机绕路");//投诉内容
                    a54.setResult("处罚20元");//处理结果
                }
                a54.save();
                System.out.println("---------------------->>>>>>>>>>ok");
            } catch (Exception e) {
                System.out.println("----------------------------->>>>>>>>>>>乘客评价接口插入失败" + list1.get(i).getOrderId());
            }

        }


        /*List<MemberComplain> memberComplainList = MemberComplain.dao.findDataAddA54();
        for (MemberComplain memberComplain : memberComplainList) {
            try {
                A54 a54 = new A54();
                a54.setOrderId(memberComplain.getOrderId());//订单号
                a54.setComplaintTime(memberComplain.getComplaintTime());//投诉时间
                a54.setDetail(memberComplain.getDetail());//投诉内容
                a54.setResult(memberComplain.getResult());//处理结果
            } catch (Exception e) {
                System.out.println("订单号:" + memberComplain.getOrderId() + " 插入表A54失败");
            }
        }*/
    }
}
