package models.portModels;


import utils.DateUtil;
import annotation.TableBind;
import base.portModels.BaseA56;
import models.driver.DriverInfo;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A56")
public class A56 extends BaseA56<A56> {
	public static final A56 dao = new A56();
	public List<A56> findCompany(){
		return  find("Select * from A56");
	}

	public void setInfos() {
		List<DriverInfo> driverInfos = DriverInfo.dao.PunishDriver();
		for (DriverInfo driverInfo : driverInfos) {
			try {
				A56 a56 = new A56();
				a56.setLicenseId((String) driverInfo.get("LicenseId"));
				a56.setPunishReason((String) driverInfo.get("Detail"));
				a56.setPunishResult("处罚20元");
				a56.setPunishTime(DateUtil.dateToLong(new Date()));
				a56.save();
			}catch (Exception e){
				System.out.println("司机手机号码："+driverInfo.get("phone")+"插入A56错误");
				continue;
			}

		}

	}

}
