package models.portModels;


import annotation.TableBind;
import base.portModels.BaseA58;
import models.driver.DriverInfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A58")
public class A58 extends BaseA58<A58> {
	public static final A58 dao = new A58();
	public List<A58> findCompany(){
		return  find("Select * from A58");
	}

	public void setInfos() {
		List<DriverInfo> driverInfos = DriverInfo.dao.ratedDriver();
		for (DriverInfo driverInfo : driverInfos) {
			try {
				A58 A58 = new A58();
				A58.setLicenseId((String) driverInfo.get("LicenseId"));
				A58.setLevel(5);
				A58.setTestDepartment("安徽省合肥市司机点点运营中心");
				A58.setTestDate(Long.valueOf("20170719"));
				A58.save();
			}catch (Exception e){
				System.out.println("司机手机号码："+driverInfo.get("phone")+"插入A58错误");
				continue;
			}

		}

	}
}
