package models.portModels;

import annotation.TableBind;
import  base.portModels.BaseA6;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A6")
public class A6 extends BaseA6<A6> {
	public static final A6 dao = new A6();
	public List<A6> findCompany(){
		return  find("Select * from A6");
	}
}
