package models.portModels;


import annotation.TableBind;
import base.portModels.BaseA60;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A60")
public class A60 extends BaseA60<A60> {
	public static final A60 dao = new A60();
	public List<A60> findCompany(){
		return  find("Select * from A60");
	}
}
