package models.portModels;

import annotation.TableBind;
import base.portModels.BaseA8;

import java.util.List;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "A8")
public class A8 extends BaseA8<A8> {
	public static final A8 dao = new A8();
	public List<A8> findCompany(){
		return  find("Select * from A8");
	}
}
