package models.sys;


import annotation.TableBind;
import base.models.BaseAlarm;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "dele_alarm")
public class Alarm extends BaseAlarm<Alarm> {
    public static final Alarm dao = new Alarm();
}
