package models.sys;


import annotation.TableBind;
import base.models.BaseApplog;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "dele_applog")
public class Applog extends BaseApplog<Applog> {
	public static final Applog dao = new Applog();
}
