package models.sys;

import annotation.TableBind;
import base.models.BaseBaseinfoCompany;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "dele_baseinfo_company")
public class BaseInfoCompany extends BaseBaseinfoCompany<BaseInfoCompany> {
	public static final BaseInfoCompany dao = new BaseInfoCompany();

	public BaseInfoCompany findCompany(){
		return  findFirst("Select * from dele_baseinfo_company");
	}
}
