package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA50<M extends BaseA50<M>> extends Model<M> implements IBean {

/*    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }*/

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "VehicleNo")
    public void setVehicleNo(String VehicleNo) {
        set("VehicleNo", VehicleNo);
    }

    @JSONField(name = "VehicleNo")
    public String getVehicleNo() {
        return get("VehicleNo");
    }

    @JSONField(name = "VehicleRegionCode")
    public void setVehicleRegionCode(Integer VehicleRegionCode) {
        set("VehicleRegionCode", VehicleRegionCode);
    }

    @JSONField(name = "VehicleRegionCode")
    public Integer getVehicleRegionCode() {
        return get("VehicleRegionCode");
    }

    @JSONField(name = "PositionTime")
    public void setPositionTime(Long PositionTime) {
        set("PositionTime", PositionTime);
    }

    @JSONField(name = "PositionTime")
    public Long getPositionTime() {
        return get("PositionTime");
    }

    @JSONField(name = "Longitude")
    public void setLongitude(Long Longitude) {
        set("Longitude", Longitude);
    }

    @JSONField(name = "Longitude")
    public Long getLongitude() {
        return get("Longitude");
    }

    @JSONField(name = "Latitude")
    public void setLatitude(Long Latitude) {
        set("Latitude", Latitude);
    }

    @JSONField(name = "Latitude")
    public Long getLatitude() {
        return get("Latitude");
    }

    @JSONField(name = "Speed")
    public void setSpeed(Long Speed) {
        set("Speed", Speed);
    }

    @JSONField(name = "Speed")
    public Long getSpeed() {
        return get("Speed");
    }

    @JSONField(name = "Direction")
    public void setDirection(Long Direction) {
        set("Direction", Direction);
    }

    @JSONField(name = "Direction")
    public Long getDirection() {
        return get("Direction");
    }

    @JSONField(name = "Elevation")
    public void setElevation(Integer Elevation) {
        set("Elevation", Elevation);
    }

    @JSONField(name = "Elevation")
    public Integer getElevation() {
        return get("Elevation");
    }

    @JSONField(name = "Mileage")
    public void setMileage(Integer Mileage) {
        set("Mileage", Mileage);
    }

    @JSONField(name = "Mileage")
    public Integer getMileage() {
        return get("Mileage");
    }

    @JSONField(name = "Encrypt")
    public void setEncrypt(Integer Encrypt) {
        set("Encrypt", Encrypt);
    }

    @JSONField(name = "Encrypt")
    public Integer getEncrypt() {
        return get("Encrypt");
    }

    @JSONField(name = "WarnStatus")
    public void setWarnStatus(Integer WarnStatus) {
        set("WarnStatus", WarnStatus);
    }

    @JSONField(name = "WarnStatus")
    public Integer getWarnStatus() {
        return get("WarnStatus");
    }

    @JSONField(name = "VehStatus")
    public void setVehStatus(Integer VehStatus) {
        set("VehStatus", VehStatus);
    }

    @JSONField(name = "VehStatus")
    public Integer getVehStatus() {
        return get("VehStatus");
    }

    @JSONField(name = "BizStatus")
    public void setBizStatus(Integer BizStatus) {
        set("BizStatus", BizStatus);
    }

    @JSONField(name = "BizStatus")
    public Integer getBizStatus() {
        return get("BizStatus");
    }

    @JSONField(name = "OrderId")
    public void setOrderId(String OrderId) {
        set("OrderId", OrderId);
    }

    @JSONField(name = "OrderId")
    public String getOrderId() {
        return get("OrderId");
    }

}
