package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA58<M extends BaseA58<M>> extends Model<M> implements IBean {

/*    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }*/

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "LicenseId")
    public void setLicenseId(String LicenseId) {
        set("LicenseId", LicenseId);
    }

    @JSONField(name = "LicenseId")
    public String getLicenseId() {
        return get("LicenseId");
    }

    @JSONField(name = "Level")
    public void setLevel(Integer Level) {
        set("Level", Level);
    }

    @JSONField(name = "Level")
    public Integer getLevel() {
        return get("Level");
    }

    @JSONField(name = "TestDate")
    public void setTestDate(Long TestDate) {
        set("TestDate", TestDate);
    }

    @JSONField(name = "TestDate")
    public Long getTestDate() {
        return get("TestDate");
    }

    @JSONField(name = "TestDepartment")
    public void setTestDepartment(String TestDepartment) {
        set("TestDepartment", TestDepartment);
    }

    @JSONField(name = "TestDepartment")
    public String getTestDepartment() {
        return get("TestDepartment");
    }

}
