package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA10<M extends BaseA10<M>> extends Model<M> implements IBean {
/*
	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "ServiceName")
	public void setServiceName(String ServiceName) {
		set("ServiceName", ServiceName);
	}
	@JSONField(name = "ServiceName")
	public String getServiceName() {
		return get("ServiceName");
	}
	@JSONField(name = "ServiceNo")
	public void setServiceNo(String ServiceNo) {
		set("ServiceNo", ServiceNo);
	}
	@JSONField(name = "ServiceNo")
	public String getServiceNo() {
		return get("ServiceNo");
	}
	@JSONField(name = "DetailAddress")
	public void setDetailAddress(String DetailAddress) {
		set("DetailAddress", DetailAddress);
	}
	@JSONField(name = "DetailAddress")
	public String getDetailAddress() {
		return get("DetailAddress");
	}
	@JSONField(name = "ResponsibleName")
	public void setResponsibleName(String ResponsibleName) {
		set("ResponsibleName", ResponsibleName);
	}
	@JSONField(name = "ResponsibleName")
	public String getResponsibleName() {
		return get("ResponsibleName");
	}
	@JSONField(name = "ResponsiblePhone")
	public void setResponsiblePhone(String ResponsiblePhone) {
		set("ResponsiblePhone", ResponsiblePhone);
	}
	@JSONField(name = "ResponsiblePhone")
	public String getResponsiblePhone() {
		return get("ResponsiblePhone");
	}
	@JSONField(name = "ManagerName")
	public void setManagerName(String ManagerName) {
		set("ManagerName", ManagerName);
	}
	@JSONField(name = "ManagerName")
	public String getManagerName() {
		return get("ManagerName");
	}
	@JSONField(name = "ManagerPhone")
	public void setManagerPhone(String ManagerPhone) {
		set("ManagerPhone", ManagerPhone);
	}
	@JSONField(name = "ManagerPhone")
	public String getManagerPhone() {
		return get("ManagerPhone");
	}
	@JSONField(name = "ContactPhone")
	public void setContactPhone(String ContactPhone) {
		set("ContactPhone", ContactPhone);
	}
	@JSONField(name = "ContactPhone")
	public String getContactPhone() {
		return get("ContactPhone");
	}
	@JSONField(name = "MailAddress")
	public void setMailAddress(String MailAddress) {
		set("MailAddress", MailAddress);
	}
	@JSONField(name = "MailAddress")
	public String getMailAddress() {
		return get("MailAddress");
	}
	@JSONField(name = "State")
	public void setState(Integer State) {
		set("State", State);
	}
	@JSONField(name = "State")
	public Integer getState() {
		return get("State");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "CreateDate")
	public void setCreateDate(Long CreateDate) {
		set("CreateDate", CreateDate);
	}
	@JSONField(name = "CreateDate")
	public Long getCreateDate() {
		return get("CreateDate");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
