package base.portModels;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuertz<M extends BaseQuertz<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setDriverId(String driverId) {
		set("driverId", driverId);
	}

	public String getDriverId() {
		return get("driverId");
	}

	public void setDUpdateTiem(java.util.Date dUpdateTiem) {
		set("dUpdateTiem", dUpdateTiem);
	}

	public java.util.Date getDUpdateTiem() {
		return get("dUpdateTiem");
	}

	public void setOrderNo(String orderNo) {
		set("orderNo", orderNo);
	}

	public String getOrderNo() {
		return get("orderNo");
	}

	public void setOUpdateTime(java.util.Date oUpdateTime) {
		set("oUpdateTime", oUpdateTime);
	}

	public java.util.Date getOUpdateTime() {
		return get("oUpdateTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setPushTime(java.util.Date pushTime) {
		set("pushTime", pushTime);
	}

	public java.util.Date getPushTime() {
		return get("pushTime");
	}

}
