package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA66<M extends BaseA66<M>> extends Model<M> implements IBean {

/*    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }*/

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "Address")
    public void setAddress(Integer Address) {
        set("Address", Address);
    }

    @JSONField(name = "Address")
    public Integer getAddress() {
        return get("Address");
    }

    @JSONField(name = "RouteId")
    public void setRouteId(String RouteId) {
        set("RouteId", RouteId);
    }

    @JSONField(name = "RouteId")
    public String getRouteId() {
        return get("RouteId");
    }

    @JSONField(name = "OrderId")
    public void setOrderId(String OrderId) {
        set("OrderId", OrderId);
    }

    @JSONField(name = "OrderId")
    public String getOrderId() {
        return get("OrderId");
    }

    @JSONField(name = "DriverPhone")
    public void setDriverPhone(String DriverPhone) {
        set("DriverPhone", DriverPhone);
    }

    @JSONField(name = "DriverPhone")
    public String getDriverPhone() {
        return get("DriverPhone");
    }

    @JSONField(name = "LicenseId")
    public void setLicenseId(String LicenseId) {
        set("LicenseId", LicenseId);
    }

    @JSONField(name = "LicenseId")
    public String getLicenseId() {
        return get("LicenseId");
    }

    @JSONField(name = "VehicleNo")
    public void setVehicleNo(String VehicleNo) {
        set("VehicleNo", VehicleNo);
    }

    @JSONField(name = "VehicleNo")
    public String getVehicleNo() {
        return get("VehicleNo");
    }

    @JSONField(name = "FareType")
    public void setFareType(String FareType) {
        set("FareType", FareType);
    }

    @JSONField(name = "FareType")
    public String getFareType() {
        return get("FareType");
    }

    @JSONField(name = "BookDepartTime")
    public void setBookDepartTime(Long BookDepartTime) {
        set("BookDepartTime", BookDepartTime);
    }

    @JSONField(name = "BookDepartTime")
    public Long getBookDepartTime() {
        return get("BookDepartTime");
    }

    @JSONField(name = "DepartTime")
    public void setDepartTime(Long DepartTime) {
        set("DepartTime", DepartTime);
    }

    @JSONField(name = "DepartTime")
    public Long getDepartTime() {
        return get("DepartTime");
    }

    @JSONField(name = "Departure")
    public void setDeparture(String Departure) {
        set("Departure", Departure);
    }

    @JSONField(name = "Departure")
    public String getDeparture() {
        return get("Departure");
    }

    @JSONField(name = "DepLongitude")
    public void setDepLongitude(Long DepLongitude) {
        set("DepLongitude", DepLongitude);
    }

    @JSONField(name = "DepLongitude")
    public Long getDepLongitude() {
        return get("DepLongitude");
    }

    @JSONField(name = "DepLatitude")
    public void setDepLatitude(Long DepLatitude) {
        set("DepLatitude", DepLatitude);
    }

    @JSONField(name = "DepLatitude")
    public Long getDepLatitude() {
        return get("DepLatitude");
    }

    @JSONField(name = "DestTime")
    public void setDestTime(Long DestTime) {
        set("DestTime", DestTime);
    }

    @JSONField(name = "DestTime")
    public Long getDestTime() {
        return get("DestTime");
    }

    @JSONField(name = "Destination")
    public void setDestination(String Destination) {
        set("Destination", Destination);
    }

    @JSONField(name = "Destination")
    public String getDestination() {
        return get("Destination");
    }

    @JSONField(name = "DestLongitude")
    public void setDestLongitude(Long DestLongitude) {
        set("DestLongitude", DestLongitude);
    }

    @JSONField(name = "DestLongitude")
    public Long getDestLongitude() {
        return get("DestLongitude");
    }

    @JSONField(name = "DestLatitude")
    public void setDestLatitude(Long DestLatitude) {
        set("DestLatitude", DestLatitude);
    }

    @JSONField(name = "DestLatitude")
    public Long getDestLatitude() {
        return get("DestLatitude");
    }

    @JSONField(name = "Encrypt")
    public void setEncrypt(Integer Encrypt) {
        set("Encrypt", Encrypt);
    }

    @JSONField(name = "Encrypt")
    public Integer getEncrypt() {
        return get("Encrypt");
    }

    @JSONField(name = "DriveMile")
    public void setDriveMile(Long DriveMile) {
        set("DriveMile", DriveMile);
    }

    @JSONField(name = "DriveMile")
    public Long getDriveMile() {
        return get("DriveMile");
    }

    @JSONField(name = "DriveTime")
    public void setDriveTime(Long DriveTime) {
        set("DriveTime", DriveTime);
    }

    @JSONField(name = "DriveTime")
    public Long getDriveTime() {
        return get("DriveTime");
    }

    @JSONField(name = "FactPrice")
    public void setFactPrice(Long FactPrice) {
        set("FactPrice", FactPrice);
    }

    @JSONField(name = "FactPrice")
    public Long getFactPrice() {
        return get("FactPrice");
    }

    @JSONField(name = "Price")
    public void setPrice(Long Price) {
        set("Price", Price);
    }

    @JSONField(name = "Price")
    public Long getPrice() {
        return get("Price");
    }

    @JSONField(name = "CashPrice")
    public void setCashPrice(Long CashPrice) {
        set("CashPrice", CashPrice);
    }

    @JSONField(name = "CashPrice")
    public Long getCashPrice() {
        return get("CashPrice");
    }

    @JSONField(name = "LineName")
    public void setLineName(String LineName) {
        set("LineName", LineName);
    }

    @JSONField(name = "LineName")
    public String getLineName() {
        return get("LineName");
    }

    @JSONField(name = "LinePrice")
    public void setLinePrice(Long LinePrice) {
        set("LinePrice", LinePrice);
    }

    @JSONField(name = "LinePrice")
    public Long getLinePrice() {
        return get("LinePrice");
    }

    @JSONField(name = "BenfitPrice")
    public void setBenfitPrice(Long BenfitPrice) {
        set("BenfitPrice", BenfitPrice);
    }

    @JSONField(name = "BenfitPrice")
    public Long getBenfitPrice() {
        return get("BenfitPrice");
    }

    @JSONField(name = "ShareFuelFee")
    public void setShareFuelFee(Integer ShareFuelFee) {
        set("ShareFuelFee", ShareFuelFee);
    }

    @JSONField(name = "ShareFuelFee")
    public Integer getShareFuelFee() {
        return get("ShareFuelFee");
    }

    @JSONField(name = "ShareHighwayToll")
    public void setShareHighwayToll(Integer ShareHighwayToll) {
        set("ShareHighwayToll", ShareHighwayToll);
    }

    @JSONField(name = "ShareHighwayToll")
    public Integer getShareHighwayToll() {
        return get("ShareHighwayToll");
    }

    @JSONField(name = "PassengerTip")
    public void setPassengerTip(Integer PassengerTip) {
        set("PassengerTip", PassengerTip);
    }

    @JSONField(name = "PassengerTip")
    public Integer getPassengerTip() {
        return get("PassengerTip");
    }

    @JSONField(name = "ShareOther")
    public void setShareOther(Integer ShareOther) {
        set("ShareOther", ShareOther);
    }

    @JSONField(name = "ShareOther")
    public Integer getShareOther() {
        return get("ShareOther");
    }

    @JSONField(name = "PayState")
    public void setPayState(String PayState) {
        set("PayState", PayState);
    }

    @JSONField(name = "PayState")
    public String getPayState() {
        return get("PayState");
    }

    @JSONField(name = "PassengerNum")
    public void setPassengerNum(Integer PassengerNum) {
        set("PassengerNum", PassengerNum);
    }

    @JSONField(name = "PassengerNum")
    public Integer getPassengerNum() {
        return get("PassengerNum");
    }

    @JSONField(name = "PayTime")
    public void setPayTime(Long PayTime) {
        set("PayTime", PayTime);
    }

    @JSONField(name = "PayTime")
    public Long getPayTime() {
        return get("PayTime");
    }

    @JSONField(name = "OrderMatchTime")
    public void setOrderMatchTime(Long OrderMatchTime) {
        set("OrderMatchTime", OrderMatchTime);
    }

    @JSONField(name = "OrderMatchTime")
    public Long getOrderMatchTime() {
        return get("OrderMatchTime");
    }

}
