package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA20<M extends BaseA20<M>> extends Model<M> implements IBean {

/*	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "VehicleNo")
	public void setVehicleNo(String VehicleNo) {
		set("VehicleNo", VehicleNo);
	}
	@JSONField(name = "VehicleNo")
	public String getVehicleNo() {
		return get("VehicleNo");
	}
	@JSONField(name = "TotalMile")
	public void setTotalMile(Long TotalMile) {
		set("TotalMile", TotalMile);
	}
	@JSONField(name = "TotalMile")
	public Integer getTotalMile() {
		return get("TotalMile");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
