package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA14<M extends BaseA14<M>> extends Model<M> implements IBean {

//	public void setId(Long id) {
//		set("id", id);
//	}
//
//	public Long getId() {
//		return get("id");
//	}
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "FareType")
	public void setFareType(String FareType) {
		set("FareType", FareType);
	}
	@JSONField(name = "FareType")
	public String getFareType() {
		return get("FareType");
	}
	@JSONField(name = "FareTypeNote")
	public void setFareTypeNote(String FareTypeNote) {
		set("FareTypeNote", FareTypeNote);
	}
	@JSONField(name = "FareTypeNote")
	public String getFareTypeNote() {
		return get("FareTypeNote");
	}
	@JSONField(name = "FareValidOn")
	public void setFareValidOn(Long FareValidOn) {
		set("FareValidOn", FareValidOn);
	}
	@JSONField(name = "FareValidOn")
	public Long getFareValidOn() {
		return get("FareValidOn");
	}
	@JSONField(name = "FareValidOff")
	public void setFareValidOff(Long FareValidOff) {
		set("FareValidOff", FareValidOff);
	}
	@JSONField(name = "FareValidOff")
	public Long getFareValidOff() {
		return get("FareValidOff");
	}
	@JSONField(name = "StartFare")
	public void setStartFare(Integer StartFare) {
		set("StartFare", StartFare);
	}
	@JSONField(name = "StartFare")
	public Integer getStartFare() {
		return get("StartFare");
	}
	@JSONField(name = "StartMile")
	public void setStartMile(Integer StartMile) {
		set("StartMile", StartMile);
	}
	@JSONField(name = "StartMile")
	public Integer getStartMile() {
		return get("StartMile");
	}
	@JSONField(name = "UnitPricePerMile")
	public void setUnitPricePerMile(Integer UnitPricePerMile) {
		set("UnitPricePerMile", UnitPricePerMile);
	}
	@JSONField(name = "UnitPricePerMile")
	public Integer getUnitPricePerMile() {
		return get("UnitPricePerMile");
	}
	@JSONField(name = "UnitPricePerMinute")
	public void setUnitPricePerMinute(Integer UnitPricePerMinute) {
		set("UnitPricePerMinute", UnitPricePerMinute);
	}
	@JSONField(name = "UnitPricePerMinute")
	public Integer getUnitPricePerMinute() {
		return get("UnitPricePerMinute");
	}
	@JSONField(name = "UpPrice")
	public void setUpPrice(Integer UpPrice) {
		set("UpPrice", UpPrice);
	}
	@JSONField(name = "UpPrice")
	public Integer getUpPrice() {
		return get("UpPrice");
	}
	@JSONField(name = "UpPriceStartMile")
	public void setUpPriceStartMile(Integer UpPriceStartMile) {
		set("UpPriceStartMile", UpPriceStartMile);
	}
	@JSONField(name = "UpPriceStartMile")
	public Integer getUpPriceStartMile() {
		return get("UpPriceStartMile");
	}
	@JSONField(name = "MorningPeakTimeOn")
	public void setMorningPeakTimeOn(String MorningPeakTimeOn) {
		set("MorningPeakTimeOn", MorningPeakTimeOn);
	}
	@JSONField(name = "MorningPeakTimeOn")
	public String getMorningPeakTimeOn() {
		return get("MorningPeakTimeOn");
	}
	@JSONField(name = "MorningPeakTimeOff")
	public void setMorningPeakTimeOff(String MorningPeakTimeOff) {
		set("MorningPeakTimeOff", MorningPeakTimeOff);
	}
	@JSONField(name = "MorningPeakTimeOff")
	public String getMorningPeakTimeOff() {
		return get("MorningPeakTimeOff");
	}
	@JSONField(name = "EveningPeakTimeOn")
	public void setEveningPeakTimeOn(String EveningPeakTimeOn) {
		set("EveningPeakTimeOn", EveningPeakTimeOn);
	}
	@JSONField(name = "EveningPeakTimeOn")
	public String getEveningPeakTimeOn() {
		return get("EveningPeakTimeOn");
	}
	@JSONField(name = "EveningPeakTimeOff")
	public void setEveningPeakTimeOff(String EveningPeakTimeOff) {
		set("EveningPeakTimeOff", EveningPeakTimeOff);
	}
	@JSONField(name = "EveningPeakTimeOff")
	public String getEveningPeakTimeOff() {
		return get("EveningPeakTimeOff");
	}
	@JSONField(name = "OtherPeakTimeOn")
	public void setOtherPeakTimeOn(String OtherPeakTimeOn) {
		set("OtherPeakTimeOn", OtherPeakTimeOn);
	}
	@JSONField(name = "OtherPeakTimeOn")
	public String getOtherPeakTimeOn() {
		return get("OtherPeakTimeOn");
	}
	@JSONField(name = "OtherPeakTimeOff")
	public void setOtherPeakTimeOff(String OtherPeakTimeOff) {
		set("OtherPeakTimeOff", OtherPeakTimeOff);
	}
	@JSONField(name = "OtherPeakTimeOff")
	public String getOtherPeakTimeOff() {
		return get("OtherPeakTimeOff");
	}
	@JSONField(name = "PeakUnitPrice")
	public void setPeakUnitPrice(Integer PeakUnitPrice) {
		set("PeakUnitPrice", PeakUnitPrice);
	}
	@JSONField(name = "PeakUnitPrice")
	public Integer getPeakUnitPrice() {
		return get("PeakUnitPrice");
	}
	@JSONField(name = "PeakPriceStartMile")
	public void setPeakPriceStartMile(Integer PeakPriceStartMile) {
		set("PeakPriceStartMile", PeakPriceStartMile);
	}
	@JSONField(name = "PeakPriceStartMile")
	public Integer getPeakPriceStartMile() {
		return get("PeakPriceStartMile");
	}
	@JSONField(name = "LowSpeedPricePerMinute")
	public void setLowSpeedPricePerMinute(Integer LowSpeedPricePerMinute) {
		set("LowSpeedPricePerMinute", LowSpeedPricePerMinute);
	}
	@JSONField(name = "LowSpeedPricePerMinute")
	public Integer getLowSpeedPricePerMinute() {
		return get("LowSpeedPricePerMinute");
	}
	@JSONField(name = "NightPricePerMile")
	public void setNightPricePerMile(Integer NightPricePerMile) {
		set("NightPricePerMile", NightPricePerMile);
	}
	@JSONField(name = "NightPricePerMile")
	public Integer getNightPricePerMile() {
		return get("NightPricePerMile");
	}
	@JSONField(name = "NightPricePerMinute")
	public void setNightPricePerMinute(Integer NightPricePerMinute) {
		set("NightPricePerMinute", NightPricePerMinute);
	}
	@JSONField(name = "NightPricePerMinute")
	public Integer getNightPricePerMinute() {
		return get("NightPricePerMinute");
	}
	@JSONField(name = "OtherPrice")
	public void setOtherPrice(Integer OtherPrice) {
		set("OtherPrice", OtherPrice);
	}
	@JSONField(name = "OtherPrice")
	public Integer getOtherPrice() {
		return get("OtherPrice");
	}
	@JSONField(name = "State")
	public void setState(Integer State) {
		set("State", State);
	}
	@JSONField(name = "State")
	public Integer getState() {
		return get("State");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
