package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import models.car.CarInfo;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA16<M extends BaseA16<M>> extends Model<M> implements IBean {

//	public void setId(Long id) {
//		set("id", id);
//	}
//
//	public Long getId() {
//		return get("id");
//	}
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "VehicleNo")
	public void setVehicleNo(String VehicleNo) {
		set("VehicleNo", VehicleNo);
	}
	@JSONField(name = "VehicleNo")
	public String getVehicleNo() {
		return get("VehicleNo");
	}
	@JSONField(name = "PlateColor")
	public void setPlateColor(String PlateColor) {
		set("PlateColor", PlateColor);
	}
	@JSONField(name = "PlateColor")
	public String getPlateColor() {
		return get("PlateColor");
	}
	@JSONField(name = "Seats")
	public void setSeats(Integer Seats) {
		set("Seats", Seats);
	}
	@JSONField(name = "Seats")
	public Integer getSeats() {
		return get("Seats");
	}
	@JSONField(name = "Brand")
	public void setBrand(String Brand) {
		set("Brand", Brand);
	}
	@JSONField(name = "Brand")
	public String getBrand() {
		return get("Brand");
	}
	@JSONField(name = "Model")
	public void setModel(String Model) {
		set("Model", Model);
	}
	@JSONField(name = "Model")
	public String getModel() {
		return get("Model");
	}
	@JSONField(name = "VehicleType")
	public void setVehicleType(String VehicleType) {
		set("VehicleType", VehicleType);
	}
	@JSONField(name = "VehicleType")
	public String getVehicleType() {
		return get("VehicleType");
	}
	@JSONField(name = "OwnerName")
	public void setOwnerName(String OwnerName) {
		set("OwnerName", OwnerName);
	}
	@JSONField(name = "OwnerName")
	public String getOwnerName() {
		return get("OwnerName");
	}
	@JSONField(name = "VehicleColor")
	public void setVehicleColor(String VehicleColor) {
		set("VehicleColor", VehicleColor);
	}
	@JSONField(name = "VehicleColor")
	public String getVehicleColor() {
		return get("VehicleColor");
	}
	@JSONField(name = "EngineId")
	public void setEngineId(String EngineId) {
		set("EngineId", EngineId);
	}
	@JSONField(name = "EngineId")
	public String getEngineId() {
		return get("EngineId");
	}
	@JSONField(name = "VIN")
	public void setVIN(String VIN) {
		set("VIN", VIN);
	}
	@JSONField(name = "VIN")
	public String getVIN() {
		return get("VIN");
	}
	@JSONField(name = "CertifyDateA")
	public void setCertifyDateA(Long CertifyDateA) {
		set("CertifyDateA", CertifyDateA);
	}
	@JSONField(name = "CertifyDateA")
	public Long getCertifyDateA() {
		return get("CertifyDateA");
	}
	@JSONField(name = "FuelType")
	public void setFuelType(String FuelType) {
		set("FuelType", FuelType);
	}
	@JSONField(name = "FuelType")
	public String getFuelType() {
		return get("FuelType");
	}
	@JSONField(name = "EngineDisplace")
	public void setEngineDisplace(String EngineDisplace) {
		set("EngineDisplace", EngineDisplace);
	}
	@JSONField(name = "EngineDisplace")
	public String getEngineDisplace() {
		return get("EngineDisplace");
	}
	@JSONField(name = "PhotoId")
	public void setPhotoId(String PhotoId) {
		set("PhotoId", PhotoId);
	}
	@JSONField(name = "PhotoId")
	public String getPhotoId() {
		return get("PhotoId");
	}
	@JSONField(name = "Certificate")
	public void setCertificate(String Certificate) {
		set("Certificate", Certificate);
	}
	@JSONField(name = "Certificate")
	public String getCertificate() {
		return get("Certificate");
	}
	@JSONField(name = "TransAgency")
	public void setTransAgency(String TransAgency) {
		set("TransAgency", TransAgency);
	}
	@JSONField(name = "TransAgency")
	public String getTransAgency() {
		return get("TransAgency");
	}
	@JSONField(name = "TransArea")
	public void setTransArea(String TransArea) {
		set("TransArea", TransArea);
	}
	@JSONField(name = "TransArea")
	public String getTransArea() {
		return get("TransArea");
	}
	@JSONField(name = "TransDateStart")
	public void setTransDateStart(Long TransDateStart) {
		set("TransDateStart", TransDateStart);
	}
	@JSONField(name = "TransDateStart")
	public Long getTransDateStart() {
		return get("TransDateStart");
	}
	@JSONField(name = "TransDateStop")
	public void setTransDateStop(Long TransDateStop) {
		set("TransDateStop", TransDateStop);
	}
	@JSONField(name = "TransDateStop")
	public Long getTransDateStop() {
		return get("TransDateStop");
	}
	@JSONField(name = "CertifyDateB")
	public void setCertifyDateB(Long CertifyDateB) {
		set("CertifyDateB", CertifyDateB);
	}
	@JSONField(name = "CertifyDateB")
	public Long getCertifyDateB() {
		return get("CertifyDateB");
	}
	@JSONField(name = "FixState")
	public void setFixState(String FixState) {
		set("FixState", FixState);
	}
	@JSONField(name = "FixState")
	public String getFixState() {
		return get("FixState");
	}
	@JSONField(name = "NextFixDate")
	public void setNextFixDate(Long NextFixDate) {
		set("NextFixDate", NextFixDate);
	}
	@JSONField(name = "NextFixDate")
	public Long getNextFixDate() {
		return get("NextFixDate");
	}
	@JSONField(name = "CheckState")
	public void setCheckState(String CheckState) {
		set("CheckState", CheckState);
	}
	@JSONField(name = "CheckState")
	public String getCheckState() {
		return get("CheckState");
	}
	@JSONField(name = "FeePrintId")
	public void setFeePrintId(String FeePrintId) {
		set("FeePrintId", FeePrintId);
	}
	@JSONField(name = "FeePrintId")
	public String getFeePrintId() {
		return get("FeePrintId");
	}
	@JSONField(name = "GPSBrand")
	public void setGPSBrand(String GPSBrand) {
		set("GPSBrand", GPSBrand);
	}
	@JSONField(name = "GPSBrand")
	public String getGPSBrand() {
		return get("GPSBrand");
	}
	@JSONField(name = "GPSModel")
	public void setGPSModel(String GPSModel) {
		set("GPSModel", GPSModel);
	}
	@JSONField(name = "GPSModel")
	public String getGPSModel() {
		return get("GPSModel");
	}
	@JSONField(name = "GPSIMEI")
	public void setGPSIMEI(String GPSIMEI) {
		set("GPSIMEI", GPSIMEI);
	}
	@JSONField(name = "GPSIMEI")
	public String getGPSIMEI() {
		return get("GPSIMEI");
	}
	@JSONField(name = "GPSInstallDate")
	public void setGPSInstallDate(Long GPSInstallDate) {
		set("GPSInstallDate", GPSInstallDate);
	}
	@JSONField(name = "GPSInstallDate")
	public Long getGPSInstallDate() {
		return get("GPSInstallDate");
	}
	@JSONField(name = "RegisterDate")
	public void setRegisterDate(Long RegisterDate) {
		set("RegisterDate", RegisterDate);
	}
	@JSONField(name = "RegisterDate")
	public Long getRegisterDate() {
		return get("RegisterDate");
	}
	@JSONField(name = "CommercialType")
	public void setCommercialType(Integer CommercialType) {
		set("CommercialType", CommercialType);
	}
	@JSONField(name = "CommercialType")
	public Integer getCommercialType() {
		return get("CommercialType");
	}
	@JSONField(name = "FareType")
	public void setFareType(String FareType) {
		set("FareType", FareType);
	}
	@JSONField(name = "FareType")
	public String getFareType() {
		return get("FareType");
	}
	@JSONField(name = "State")
	public void setState(Integer State) {
		set("State", State);
	}
	@JSONField(name = "State")
	public Integer getState() {
		return get("State");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
