package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA42<M extends BaseA42<M>> extends Model<M> implements IBean {

	/*public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}

	@JSONField(name = "OrderId")
	public void setOrderId(String OrderId) {
		set("OrderId", OrderId);
	}
	@JSONField(name = "OrderId")
	public String getOrderId() {
		return get("OrderId");
	}

	@JSONField(name = "LicenseId")
	public void setLicenseId(String LicenseId) {
		set("LicenseId", LicenseId);
	}
	@JSONField(name = "LicenseId")
	public String getLicenseId() {
		return get("LicenseId");
	}

	@JSONField(name = "FareType")
	public void setFareType(String FareType) {
		set("FareType", FareType);
	}
	@JSONField(name = "FareType")
	public String getFareType() {
		return get("FareType");
	}

	@JSONField(name = "VehicleNo")
	public void setVehicleNo(String VehicleNo) {
		set("VehicleNo", VehicleNo);
	}
	@JSONField(name = "VehicleNo")
	public String getVehicleNo() {
		return get("VehicleNo");
	}

	@JSONField(name = "DepLongitude")
	public void setDepLongitude(Long DepLongitude) {
		set("DepLongitude", DepLongitude);
	}
	@JSONField(name = "DepLongitude")
	public Long getDepLongitude() {
		return get("DepLongitude");
	}

	@JSONField(name = "DepLatitude")
	public void setDepLatitude(Long DepLatitude) {
		set("DepLatitude", DepLatitude);
	}
	@JSONField(name = "DepLatitude")
	public Long getDepLatitude() {
		return get("DepLatitude");
	}

	@JSONField(name = "Encrypt")
	public void setEncrypt(Integer Encrypt) {
		set("Encrypt", Encrypt);
	}
	@JSONField(name = "Encrypt")
	public Integer getEncrypt() {
		return get("Encrypt");
	}

	@JSONField(name = "DepTime")
	public void setDepTime(Long DepTime) {
		set("DepTime", DepTime);
	}
	@JSONField(name = "DepTime")
	public Long getDepTime() {
		return get("DepTime");
	}

	@JSONField(name = "WaitMile")
	public void setWaitMile(Integer WaitMile) {
		set("WaitMile", WaitMile);
	}
	@JSONField(name = "WaitMile")
	public Integer getWaitMile() {
		return get("WaitMile");
	}

	@JSONField(name = "WaitTime")
	public void setWaitTime(Integer WaitTime) {
		set("WaitTime", WaitTime);
	}
	@JSONField(name = "WaitTime")
	public Integer getWaitTime() {
		return get("WaitTime");
	}

}
