package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA28<M extends BaseA28<M>> extends Model<M> implements IBean {

	/*public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}

	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}

	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}

	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}

	@JSONField(name = "LicenseId")
	public void setLicenseId(String LicenseId) {
		set("LicenseId", LicenseId);
	}

	@JSONField(name = "LicenseId")
	public String getLicenseId() {
		return get("LicenseId");
	}

	@JSONField(name = "Cycle")
	public void setCycle(Integer Cycle) {
		set("Cycle", Cycle);
	}

	@JSONField(name = "Cycle")
	public Integer getCycle() {
		return get("Cycle");
	}

	@JSONField(name = "OrderCount")
	public void setOrderCount(Integer OrderCount) {
		set("OrderCount", OrderCount);
	}

	@JSONField(name = "OrderCount")
	public Integer getOrderCount() {
		return get("OrderCount");
	}

	@JSONField(name = "TrafficViolationCount")
	public void setTrafficViolationCount(Integer TrafficViolationCount) {
		set("TrafficViolationCount", TrafficViolationCount);
	}

	@JSONField(name = "TrafficViolationCount")
	public Integer getTrafficViolationCount() {
		return get("TrafficViolationCount");
	}

	@JSONField(name = "ComplainedCount")
	public void setComplainedCount(Integer ComplainedCount) {
		set("ComplainedCount", ComplainedCount);
	}

	@JSONField(name = "ComplainedCount")
	public Integer getComplainedCount() {
		return get("ComplainedCount");
	}

	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}

	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}

	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}

	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
