package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA22<M extends BaseA22<M>> extends Model<M> implements IBean {

/*	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "DriverName")
	public void setDriverName(String DriverName) {
		set("DriverName", DriverName);
	}
	@JSONField(name = "DriverName")
	public String getDriverName() {
		return get("DriverName");
	}
	@JSONField(name = "DriverPhone")
	public void setDriverPhone(String DriverPhone) {
		set("DriverPhone", DriverPhone);
	}
	@JSONField(name = "DriverPhone")
	public String getDriverPhone() {
		return get("DriverPhone");
	}
	@JSONField(name = "DriverGender")
	public void setDriverGender(String DriverGender) {
		set("DriverGender", DriverGender);
	}
	@JSONField(name = "DriverGender")
	public String getDriverGender() {
		return get("DriverGender");
	}
	@JSONField(name = "DriverBirthday")
	public void setDriverBirthday(Long DriverBirthday) {
		set("DriverBirthday", DriverBirthday);
	}
	@JSONField(name = "DriverBirthday")
	public Long getDriverBirthday() {
		return get("DriverBirthday");
	}
	@JSONField(name = "DriverNationality")
	public void setDriverNationality(String DriverNationality) {
		set("DriverNationality", DriverNationality);
	}
	@JSONField(name = "DriverNationality")
	public String getDriverNationality() {
		return get("DriverNationality");
	}
	@JSONField(name = "DriverNation")
	public void setDriverNation(String DriverNation) {
		set("DriverNation", DriverNation);
	}
	@JSONField(name = "DriverNation")
	public String getDriverNation() {
		return get("DriverNation");
	}
	@JSONField(name = "DriverMaritalStatus")
	public void setDriverMaritalStatus(String DriverMaritalStatus) {
		set("DriverMaritalStatus", DriverMaritalStatus);
	}
	@JSONField(name = "DriverMaritalStatus")
	public String getDriverMaritalStatus() {
		return get("DriverMaritalStatus");
	}
	@JSONField(name = "DriverLanguageLevel")
	public void setDriverLanguageLevel(String DriverLanguageLevel) {
		set("DriverLanguageLevel", DriverLanguageLevel);
	}
	@JSONField(name = "DriverLanguageLevel")
	public String getDriverLanguageLevel() {
		return get("DriverLanguageLevel");
	}
	@JSONField(name = "DriverEducation")
	public void setDriverEducation(String DriverEducation) {
		set("DriverEducation", DriverEducation);
	}
	@JSONField(name = "DriverEducation")
	public String getDriverEducation() {
		return get("DriverEducation");
	}
	@JSONField(name = "DriverCensus")
	public void setDriverCensus(String DriverCensus) {
		set("DriverCensus", DriverCensus);
	}
	@JSONField(name = "DriverCensus")
	public String getDriverCensus() {
		return get("DriverCensus");
	}
	@JSONField(name = "DriverAddress")
	public void setDriverAddress(String DriverAddress) {
		set("DriverAddress", DriverAddress);
	}
	@JSONField(name = "DriverAddress")
	public String getDriverAddress() {
		return get("DriverAddress");
	}
	@JSONField(name = "DriverContactAddress")
	public void setDriverContactAddress(String DriverContactAddress) {
		set("DriverContactAddress", DriverContactAddress);
	}
	@JSONField(name = "DriverContactAddress")
	public String getDriverContactAddress() {
		return get("DriverContactAddress");
	}
	@JSONField(name = "PhotoId")
	public void setPhotoId(String PhotoId) {
		set("PhotoId", PhotoId);
	}
	@JSONField(name = "PhotoId")
	public String getPhotoId() {
		return get("PhotoId");
	}
	@JSONField(name = "LicenseId")
	public void setLicenseId(String LicenseId) {
		set("LicenseId", LicenseId);
	}
	@JSONField(name = "LicenseId")
	public String getLicenseId() {
		return get("LicenseId");
	}
	@JSONField(name = "LicensePhotoId")
	public void setLicensePhotoId(String LicensePhotoId) {
		set("LicensePhotoId", LicensePhotoId);
	}
	@JSONField(name = "LicensePhotoId")
	public String getLicensePhotoId() {
		return get("LicensePhotoId");
	}
	@JSONField(name = "DriverType")
	public void setDriverType(String DriverType) {
		set("DriverType", DriverType);
	}
	@JSONField(name = "DriverType")
	public String getDriverType() {
		return get("DriverType");
	}
	@JSONField(name = "GetDriverLicenseDate")
	public void setGetDriverLicenseDate(Long GetDriverLicenseDate) {
		set("GetDriverLicenseDate", GetDriverLicenseDate);
	}
	@JSONField(name = "GetDriverLicenseDate")
	public Long getGetDriverLicenseDate() {
		return get("GetDriverLicenseDate");
	}
	@JSONField(name = "DriverLicenseOn")
	public void setDriverLicenseOn(Long DriverLicenseOn) {
		set("DriverLicenseOn", DriverLicenseOn);
	}
	@JSONField(name = "DriverLicenseOn")
	public Long getDriverLicenseOn() {
		return get("DriverLicenseOn");
	}
	@JSONField(name = "DriverLicenseOff")
	public void setDriverLicenseOff(Long DriverLicenseOff) {
		set("DriverLicenseOff", DriverLicenseOff);
	}
	@JSONField(name = "DriverLicenseOff")
	public Long getDriverLicenseOff() {
		return get("DriverLicenseOff");
	}
	@JSONField(name = "TaxiDriver")
	public void setTaxiDriver(Integer TaxiDriver) {
		set("TaxiDriver", TaxiDriver);
	}
	@JSONField(name = "TaxiDriver")
	public Integer getTaxiDriver() {
		return get("TaxiDriver");
	}
	@JSONField(name = "CertificateNo")
	public void setCertificateNo(String CertificateNo) {
		set("CertificateNo", CertificateNo);
	}
	@JSONField(name = "CertificateNo")
	public String getCertificateNo() {
		return get("CertificateNo");
	}
	@JSONField(name = "NetworkCarIssueOrganization")
	public void setNetworkCarIssueOrganization(String NetworkCarIssueOrganization) {
		set("NetworkCarIssueOrganization", NetworkCarIssueOrganization);
	}
	@JSONField(name = "NetworkCarIssueOrganization")
	public String getNetworkCarIssueOrganization() {
		return get("NetworkCarIssueOrganization");
	}
	@JSONField(name = "NetworkCarIssueDate")
	public void setNetworkCarIssueDate(Long NetworkCarIssueDate) {
		set("NetworkCarIssueDate", NetworkCarIssueDate);
	}
	@JSONField(name = "NetworkCarIssueDate")
	public Long getNetworkCarIssueDate() {
		return get("NetworkCarIssueDate");
	}
	@JSONField(name = "GetNetworkCarProofDate")
	public void setGetNetworkCarProofDate(Long GetNetworkCarProofDate) {
		set("GetNetworkCarProofDate", GetNetworkCarProofDate);
	}
	@JSONField(name = "GetNetworkCarProofDate")
	public Long getGetNetworkCarProofDate() {
		return get("GetNetworkCarProofDate");
	}
	@JSONField(name = "NetworkCarProofOn")
	public void setNetworkCarProofOn(Long NetworkCarProofOn) {
		set("NetworkCarProofOn", NetworkCarProofOn);
	}
	@JSONField(name = "NetworkCarProofOn")
	public Long getNetworkCarProofOn() {
		return get("NetworkCarProofOn");
	}
	@JSONField(name = "NetworkCarProofOff")
	public void setNetworkCarProofOff(Long NetworkCarProofOff) {
		set("NetworkCarProofOff", NetworkCarProofOff);
	}
	@JSONField(name = "NetworkCarProofOff")
	public Long getNetworkCarProofOff() {
		return get("NetworkCarProofOff");
	}
	@JSONField(name = "RegisterDate")
	public void setRegisterDate(Long RegisterDate) {
		set("RegisterDate", RegisterDate);
	}
	@JSONField(name = "RegisterDate")
	public Long getRegisterDate() {
		return get("RegisterDate");
	}
	@JSONField(name = "FullTimeDriver")
	public void setFullTimeDriver(Integer FullTimeDriver) {
		set("FullTimeDriver", FullTimeDriver);
	}
	@JSONField(name = "FullTimeDriver")
	public Integer getFullTimeDriver() {
		return get("FullTimeDriver");
	}
	@JSONField(name = "InDriverBlacklist")
	public void setInDriverBlacklist(Integer InDriverBlacklist) {
		set("InDriverBlacklist", InDriverBlacklist);
	}
	@JSONField(name = "InDriverBlacklist")
	public Integer getInDriverBlacklist() {
		return get("InDriverBlacklist");
	}
	@JSONField(name = "CommercialType")
	public void setCommercialType(Integer CommercialType) {
		set("CommercialType", CommercialType);
	}
	@JSONField(name = "CommercialType")
	public Integer getCommercialType() {
		return get("CommercialType");
	}
	@JSONField(name = "ContractCompany")
	public void setContractCompany(String ContractCompany) {
		set("ContractCompany", ContractCompany);
	}
	@JSONField(name = "ContractCompany")
	public String getContractCompany() {
		return get("ContractCompany");
	}
	@JSONField(name = "ContractOn")
	public void setContractOn(Long ContractOn) {
		set("ContractOn", ContractOn);
	}
	@JSONField(name = "ContractOn")
	public Long getContractOn() {
		return get("ContractOn");
	}
	@JSONField(name = "ContractOff")
	public void setContractOff(Long ContractOff) {
		set("ContractOff", ContractOff);
	}
	@JSONField(name = "ContractOff")
	public Long getContractOff() {
		return get("ContractOff");
	}
	@JSONField(name = "EmergencyContact")
	public void setEmergencyContact(String EmergencyContact) {
		set("EmergencyContact", EmergencyContact);
	}
	@JSONField(name = "EmergencyContact")
	public String getEmergencyContact() {
		return get("EmergencyContact");
	}
	@JSONField(name = "EmergencyContactPhone")
	public void setEmergencyContactPhone(String EmergencyContactPhone) {
		set("EmergencyContactPhone", EmergencyContactPhone);
	}
	@JSONField(name = "EmergencyContactPhone")
	public String getEmergencyContactPhone() {
		return get("EmergencyContactPhone");
	}
	@JSONField(name = "EmergencyContactAddress")
	public void setEmergencyContactAddress(String EmergencyContactAddress) {
		set("EmergencyContactAddress", EmergencyContactAddress);
	}
	@JSONField(name = "EmergencyContactAddress")
	public String getEmergencyContactAddress() {
		return get("EmergencyContactAddress");
	}
	@JSONField(name = "State")
	public void setState(Integer State) {
		set("State", State);
	}
	@JSONField(name = "State")
	public Integer getState() {
		return get("State");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
