package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA56<M extends BaseA56<M>> extends Model<M> implements IBean {

//    public void setId(Long id) {
//        set("id", id);
//    }
//
//    public Long getId() {
//        return get("id");
//    }

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "LicenseId")
    public void setLicenseId(String LicenseId) {
        set("LicenseId", LicenseId);
    }

    @JSONField(name = "LicenseId")
    public String getLicenseId() {
        return get("LicenseId");
    }

    @JSONField(name = "PunishTime")
    public void setPunishTime(Long PunishTime) {
        set("PunishTime", PunishTime);
    }

    @JSONField(name = "PunishTime")
    public Long getPunishTime() {
        return get("PunishTime");
    }

    @JSONField(name = "PunishReason")
    public void setPunishReason(String PunishReason) {
        set("PunishReason", PunishReason);
    }

    @JSONField(name = "PunishReason")
    public String getPunishReason() {
        return get("PunishReason");
    }

    @JSONField(name = "PunishResult")
    public void setPunishResult(String PunishResult) {
        set("PunishResult", PunishResult);
    }

    @JSONField(name = "PunishResult")
    public String getPunishResult() {
        return get("PunishResult");
    }

}
