package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA54<M extends BaseA54<M>> extends Model<M> implements IBean {

/*    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }*/

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "OrderId")
    public void setOrderId(String OrderId) {
        set("OrderId", OrderId);
    }

    @JSONField(name = "OrderId")
    public String getOrderId() {
        return get("OrderId");
    }

    @JSONField(name = "ComplaintTime")
    public void setComplaintTime(Long ComplaintTime) {
        set("ComplaintTime", ComplaintTime);
    }

    @JSONField(name = "ComplaintTime")
    public Long getComplaintTime() {
        return get("ComplaintTime");
    }

    @JSONField(name = "Detail")
    public void setDetail(String Detail) {
        set("Detail", Detail);
    }

    @JSONField(name = "Detail")
    public String getDetail() {
        return get("Detail");
    }

    @JSONField(name = "Result")
    public void setResult(String Result) {
        set("Result", Result);
    }

    @JSONField(name = "Result")
    public String getResult() {
        return get("Result");
    }

}
