package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA18<M extends BaseA18<M>> extends Model<M> implements IBean {

//	public void setId(Long id) {
//		set("id", id);
//	}

//	public Long getId() {
//		return get("id");
//	}
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "VehicleNo")
	public void setVehicleNo(String VehicleNo) {
		set("VehicleNo", VehicleNo);
	}
	@JSONField(name = "VehicleNo")
	public String getVehicleNo() {
		return get("VehicleNo");
	}
	@JSONField(name = "InsurCom")
	public void setInsurCom(String InsurCom) {
		set("InsurCom", InsurCom);
	}
	@JSONField(name = "InsurCom")
	public String getInsurCom() {
		return get("InsurCom");
	}
	@JSONField(name = "InsurNum")
	public void setInsurNum(String InsurNum) {
		set("InsurNum", InsurNum);
	}
	@JSONField(name = "InsurNum")
	public String getInsurNum() {
		return get("InsurNum");
	}
	@JSONField(name = "InsurType")
	public void setInsurType(String InsurType) {
		set("InsurType", InsurType);
	}
	@JSONField(name = "InsurType")
	public String getInsurType() {
		return get("InsurType");
	}
	@JSONField(name = "InsurCount")
	public void setInsurCount(Integer InsurCount) {
		set("InsurCount", InsurCount);
	}
	@JSONField(name = "InsurCount")
	public Integer getInsurCount() {
		return get("InsurCount");
	}
	@JSONField(name = "InsurEff")
	public void setInsurEff(Integer InsurEff) {
		set("InsurEff", InsurEff);
	}
	@JSONField(name = "InsurEff")
	public Integer getInsurEff() {
		return get("InsurEff");
	}
	@JSONField(name = "InsurExp")
	public void setInsurExp(Integer InsurExp) {
		set("InsurExp", InsurExp);
	}
	@JSONField(name = "InsurExp")
	public Integer getInsurExp() {
		return get("InsurExp");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
