package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA12<M extends BaseA12<M>> extends Model<M> implements IBean {

//	public void setId(Long id) {
//		set("id", id);
//	}
//
//	public Long getId() {
//		return get("id");
//	}
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "Certificate")
	public void setCertificate(String Certificate) {
		set("Certificate", Certificate);
	}
	@JSONField(name = "Certificate")
	public String getCertificate() {
		return get("Certificate");
	}
	@JSONField(name = "OperationArea")
	public void setOperationArea(String OperationArea) {
		set("OperationArea", OperationArea);
	}
	@JSONField(name = "OperationArea")
	public String getOperationArea() {
		return get("OperationArea");
	}
	@JSONField(name = "OwnerName")
	public void setOwnerName(String OwnerName) {
		set("OwnerName", OwnerName);
	}
	@JSONField(name = "OwnerName")
	public String getOwnerName() {
		return get("OwnerName");
	}
	@JSONField(name = "Organization")
	public void setOrganization(String Organization) {
		set("Organization", Organization);
	}
	@JSONField(name = "Organization")
	public String getOrganization() {
		return get("Organization");
	}
	@JSONField(name = "StartDate")
	public void setStartDate(Long StartDate) {
		set("StartDate", StartDate);
	}
	@JSONField(name = "StartDate")
	public Long getStartDate() {
		return get("StartDate");
	}
	@JSONField(name = "StopDate")
	public void setStopDate(Long StopDate) {
		set("StopDate", StopDate);
	}
	@JSONField(name = "StopDate")
	public Long getStopDate() {
		return get("StopDate");
	}
	@JSONField(name = "CertifyDate")
	public void setCertifyDate(Long CertifyDate) {
		set("CertifyDate", CertifyDate);
	}
	@JSONField(name = "CertifyDate")
	public Long getCertifyDate() {
		return get("CertifyDate");
	}
	@JSONField(name = "State")
	public void setState(String State) {
		set("State", State);
	}
	@JSONField(name = "State")
	public String getState() {
		return get("State");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
