package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA44<M extends BaseA44<M>> extends Model<M> implements IBean {

	/*public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/

	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}

	@JSONField(name = "OrderId")
	public void setOrderId(String OrderId) {
		set("OrderId", OrderId);
	}
	@JSONField(name = "OrderId")
	public String getOrderId() {
		return get("OrderId");
	}

	@JSONField(name = "DestLongitude")
	public void setDestLongitude(Long DestLongitude) {
		set("DestLongitude", DestLongitude);
	}
	@JSONField(name = "DestLongitude")
	public Long getDestLongitude() {
		return get("DestLongitude");
	}

	@JSONField(name = "DestLatitude")
	public void setDestLatitude(Long DestLatitude) {
		set("DestLatitude", DestLatitude);
	}
	@JSONField(name = "DestLatitude")
	public Long getDestLatitude() {
		return get("DestLatitude");
	}

	@JSONField(name = "Encrypt")
	public void setEncrypt(Integer Encrypt) {
		set("Encrypt", Encrypt);
	}
	@JSONField(name = "Encrypt")
	public Integer getEncrypt() {
		return get("Encrypt");
	}

	@JSONField(name = "DestTime")
	public void setDestTime(Long DestTime) {
		set("DestTime", DestTime);
	}
	@JSONField(name = "DestTime")
	public Long getDestTime() {
		return get("DestTime");
	}

	@JSONField(name = "DriveMile")
	public void setDriveMile(Long DriveMile) {
		set("DriveMile", DriveMile);
	}
	@JSONField(name = "DriveMile")
	public Long getDriveMile() {
		return get("DriveMile");
	}

	@JSONField(name = "DriveTime")
	public void setDriveTime(Integer DriveTime) {
		set("DriveTime", DriveTime);
	}
	@JSONField(name = "DriveTime")
	public Integer getDriveTime() {
		return get("DriveTime");
	}

}
