package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA26<M extends BaseA26<M>> extends Model<M> implements IBean {

//    public void setId(Long id) {
//        set("id", id);
//    }
//
//    public Long getId() {
//        return get("id");
//    }

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "Address")
    public void setAddress(Integer Address) {
        set("Address", Address);
    }

    @JSONField(name = "Address")
    public Integer getAddress() {
        return get("Address");
    }

    @JSONField(name = "LicenseId")
    public void setLicenseId(String LicenseId) {
        set("LicenseId", LicenseId);
    }

    @JSONField(name = "LicenseId")
    public String getLicenseId() {
        return get("LicenseId");
    }

    @JSONField(name = "DriverPhone")
    public void setDriverPhone(String DriverPhone) {
        set("DriverPhone", DriverPhone);
    }

    @JSONField(name = "DriverPhone")
    public String getDriverPhone() {
        return get("DriverPhone");
    }

    @JSONField(name = "NetType")
    public void setNetType(Integer NetType) {
        set("NetType", NetType);
    }

    @JSONField(name = "NetType")
    public Integer getNetType() {
        return get("NetType");
    }

    @JSONField(name = "AppVersion")
    public void setAppVersion(String AppVersion) {
        set("AppVersion", AppVersion);
    }

    @JSONField(name = "AppVersion")
    public String getAppVersion() {
        return get("AppVersion");
    }

    @JSONField(name = "MapType")
    public void setMapType(Integer MapType) {
        set("MapType", MapType);
    }

    @JSONField(name = "MapType")
    public Integer getMapType() {
        return get("MapType");
    }

    @JSONField(name = "State")
    public void setState(Integer State) {
        set("State", State);
    }

    @JSONField(name = "State")
    public Integer getState() {
        return get("State");
    }

    @JSONField(name = "Flag")
    public void setFlag(Integer Flag) {
        set("Flag", Flag);
    }

    @JSONField(name = "Flag")
    public Integer getFlag() {
        return get("Flag");
    }

    @JSONField(name = "UpdateTime")
    public void setUpdateTime(Long UpdateTime) {
        set("UpdateTime", UpdateTime);
    }

    @JSONField(name = "UpdateTime")
    public Long getUpdateTime() {
        return get("UpdateTime");
    }

}
