package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA32<M extends BaseA32<M>> extends Model<M> implements IBean {

//	public void setId(Long id) {
//		set("id", id);
//	}
//
//	public Long getId() {
//		return get("id");
//	}

	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}

	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}

	@JSONField(name = "OrderId")
	public void setOrderId(String OrderId) {
		set("OrderId", OrderId);
	}
	@JSONField(name = "OrderId")
	public String getOrderId() {
		return get("OrderId");
	}

	@JSONField(name = "DepartTime")
	public void setDepartTime(Long DepartTime) {
		set("DepartTime", DepartTime);
	}
	@JSONField(name = "DepartTime")
	public Long getDepartTime() {
		return get("DepartTime");
	}

	@JSONField(name = "OrderTime")
	public void setOrderTime(Long OrderTime) {
		set("OrderTime", OrderTime);
	}
	@JSONField(name = "OrderTime")
	public Long getOrderTime() {
		return get("OrderTime");
	}

	@JSONField(name = "PassengerNote")
	public void setPassengerNote(String PassengerNote) {
		set("PassengerNote", PassengerNote);
	}
	@JSONField(name = "PassengerNote")
	public String getPassengerNote() {
		return get("PassengerNote");
	}

	@JSONField(name = "Departure")
	public void setDeparture(String Departure) {
		set("Departure", Departure);
	}
	@JSONField(name = "Departure")
	public String getDeparture() {
		return get("Departure");
	}

	@JSONField(name = "DepLongitude")
	public void setDepLongitude(Long DepLongitude) {
		set("DepLongitude", DepLongitude);
	}
	@JSONField(name = "DepLongitude")
	public Long getDepLongitude() {
		return get("DepLongitude");
	}

	@JSONField(name = "DepLatitude")
	public void setDepLatitude(Long DepLatitude) {
		set("DepLatitude", DepLatitude);
	}
	@JSONField(name = "DepLatitude")
	public Long getDepLatitude() {
		return get("DepLatitude");
	}

	@JSONField(name = "Destination")
	public void setDestination(String Destination) {
		set("Destination", Destination);
	}
	@JSONField(name = "Destination")
	public String getDestination() {
		return get("Destination");
	}

	@JSONField(name = "DestLongitude")
	public void setDestLongitude(Long DestLongitude) {
		set("DestLongitude", DestLongitude);
	}
	@JSONField(name = "DestLongitude")
	public Long getDestLongitude() {
		return get("DestLongitude");
	}

	@JSONField(name = "DestLatitude")
	public void setDestLatitude(Long DestLatitude) {
		set("DestLatitude", DestLatitude);
	}
	@JSONField(name = "DestLatitude")
	public Long getDestLatitude() {
		return get("DestLatitude");
	}

	@JSONField(name = "Encrypt")
	public void setEncrypt(Integer Encrypt) {
		set("Encrypt", Encrypt);
	}
	@JSONField(name = "Encrypt")
	public Integer getEncrypt() {
		return get("Encrypt");
	}

	@JSONField(name = "FareType")
	public void setFareType(String FareType) {
		set("FareType", FareType);
	}
	@JSONField(name = "FareType")
	public String getFareType() {
		return get("FareType");
	}

}
