package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA36<M extends BaseA36<M>> extends Model<M> implements IBean {

	/*public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/

	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}

	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}

	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}

	@JSONField(name = "OrderId")
	public void setOrderId(String OrderId) {
		set("OrderId", OrderId);
	}
	@JSONField(name = "OrderId")
	public String getOrderId() {
		return get("OrderId");
	}

	@JSONField(name = "OrderTime")
	public void setOrderTime(Long OrderTime) {
		set("OrderTime", OrderTime);
	}
	@JSONField(name = "OrderTime")
	public Long getOrderTime() {
		return get("OrderTime");
	}

	@JSONField(name = "CancelTime")
	public void setCancelTime(Long CancelTime) {
		set("CancelTime", CancelTime);
	}
	@JSONField(name = "CancelTime")
	public Long getCancelTime() {
		return get("CancelTime");
	}

	@JSONField(name = "Operator")
	public void setOperator(String Operator) {
		set("Operator", Operator);
	}
	@JSONField(name = "Operator")
	public String getOperator() {
		return get("Operator");
	}

	@JSONField(name = "CancelTypeCode")
	public void setCancelTypeCode(String CancelTypeCode) {
		set("CancelTypeCode", CancelTypeCode);
	}
	@JSONField(name = "CancelTypeCode")
	public String getCancelTypeCode() {
		return get("CancelTypeCode");
	}

	@JSONField(name = "CancelReason")
	public void setCancelReason(String CancelReason) {
		set("CancelReason", CancelReason);
	}
	@JSONField(name = "CancelReason")
	public String getCancelReason() {
		return get("CancelReason");
	}

}
