package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA24<M extends BaseA24<M>> extends Model<M> implements IBean {

	/*public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}*/
	@JSONField(name = "CompanyId")
	public void setCompanyId(String CompanyId) {
		set("CompanyId", CompanyId);
	}
	@JSONField(name = "CompanyId")
	public String getCompanyId() {
		return get("CompanyId");
	}
	@JSONField(name = "Address")
	public void setAddress(Integer Address) {
		set("Address", Address);
	}
	@JSONField(name = "Address")
	public Integer getAddress() {
		return get("Address");
	}
	@JSONField(name = "LicenseId")
	public void setLicenseId(String LicenseId) {
		set("LicenseId", LicenseId);
	}
	@JSONField(name = "LicenseId")
	public String getLicenseId() {
		return get("LicenseId");
	}
	@JSONField(name = "CourseName")
	public void setCourseName(String CourseName) {
		set("CourseName", CourseName);
	}
	@JSONField(name = "CourseName")
	public String getCourseName() {
		return get("CourseName");
	}
	@JSONField(name = "CourseDate")
	public void setCourseDate(Integer CourseDate) {
		set("CourseDate", CourseDate);
	}
	@JSONField(name = "CourseDate")
	public Integer getCourseDate() {
		return get("CourseDate");
	}
	@JSONField(name = "StartTime")
	public void setStartTime(String StartTime) {
		set("StartTime", StartTime);
	}
	@JSONField(name = "StartTime")
	public String getStartTime() {
		return get("StartTime");
	}
	@JSONField(name = "StopTime")
	public void setStopTime(String StopTime) {
		set("StopTime", StopTime);
	}
	@JSONField(name = "StopTime")
	public String getStopTime() {
		return get("StopTime");
	}
	@JSONField(name = "Duration")
	public void setDuration(Long Duration) {
		set("Duration", Duration);
	}
	@JSONField(name = "Duration")
	public Long getDuration() {
		return get("Duration");
	}
	@JSONField(name = "Flag")
	public void setFlag(Integer Flag) {
		set("Flag", Flag);
	}
	@JSONField(name = "Flag")
	public Integer getFlag() {
		return get("Flag");
	}
	@JSONField(name = "UpdateTime")
	public void setUpdateTime(Long UpdateTime) {
		set("UpdateTime", UpdateTime);
	}
	@JSONField(name = "UpdateTime")
	public Long getUpdateTime() {
		return get("UpdateTime");
	}

}
