package base.portModels;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseA46<M extends BaseA46<M>> extends Model<M> implements IBean {

/*    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }*/

    @JSONField(name = "CompanyId")
    public void setCompanyId(String CompanyId) {
        set("CompanyId", CompanyId);
    }

    @JSONField(name = "CompanyId")
    public String getCompanyId() {
        return get("CompanyId");
    }

    @JSONField(name = "OrderId")
    public void setOrderId(String OrderId) {
        set("OrderId", OrderId);
    }

    @JSONField(name = "OrderId")
    public String getOrderId() {
        return get("OrderId");
    }

    @JSONField(name = "OnArea")
    public void setOnArea(Integer OnArea) {
        set("OnArea", OnArea);
    }

    @JSONField(name = "OnArea")
    public Integer getOnArea() {
        return get("OnArea");
    }

    @JSONField(name = "DriverName")
    public void setDriverName(String DriverName) {
        set("DriverName", DriverName);
    }

    @JSONField(name = "DriverName")
    public String getDriverName() {
        return get("DriverName");
    }

    @JSONField(name = "LicenseId")
    public void setLicenseId(String LicenseId) {
        set("LicenseId", LicenseId);
    }

    @JSONField(name = "LicenseId")
    public String getLicenseId() {
        return get("LicenseId");
    }

    @JSONField(name = "FareType")
    public void setFareType(String FareType) {
        set("FareType", FareType);
    }

    @JSONField(name = "FareType")
    public String getFareType() {
        return get("FareType");
    }

    @JSONField(name = "VehicleNo")
    public void setVehicleNo(String VehicleNo) {
        set("VehicleNo", VehicleNo);
    }

    @JSONField(name = "VehicleNo")
    public String getVehicleNo() {
        return get("VehicleNo");
    }

    @JSONField(name = "BookDepTime")
    public void setBookDepTime(Long BookDepTime) {
        set("BookDepTime", BookDepTime);
    }

    @JSONField(name = "BookDepTime")
    public Long getBookDepTime() {
        return get("BookDepTime");
    }

    @JSONField(name = "WaitTime")
    public void setWaitTime(Long WaitTime) {
        set("WaitTime", WaitTime);
    }

    @JSONField(name = "WaitTime")
    public Long getWaitTime() {
        return get("WaitTime");
    }

    @JSONField(name = "DepLongitude")
    public void setDepLongitude(Long DepLongitude) {
        set("DepLongitude", DepLongitude);
    }

    @JSONField(name = "DepLongitude")
    public Long getDepLongitude() {
        return get("DepLongitude");
    }

    @JSONField(name = "DepLatitude")
    public void setDepLatitude(Long DepLatitude) {
        set("DepLatitude", DepLatitude);
    }

    @JSONField(name = "DepLatitude")
    public Long getDepLatitude() {
        return get("DepLatitude");
    }

    @JSONField(name = "DepArea")
    public void setDepArea(String DepArea) {
        set("DepArea", DepArea);
    }

    @JSONField(name = "DepArea")
    public String getDepArea() {
        return get("DepArea");
    }

    @JSONField(name = "DepTime")
    public void setDepTime(Long DepTime) {
        set("DepTime", DepTime);
    }

    @JSONField(name = "DepTime")
    public Long getDepTime() {
        return get("DepTime");
    }

    @JSONField(name = "DestLongitude")
    public void setDestLongitude(Long DestLongitude) {
        set("DestLongitude", DestLongitude);
    }

    @JSONField(name = "DestLongitude")
    public Long getDestLongitude() {
        return get("DestLongitude");
    }

    @JSONField(name = "DestLatitude")
    public void setDestLatitude(Long DestLatitude) {
        set("DestLatitude", DestLatitude);
    }

    @JSONField(name = "DestLatitude")
    public Long getDestLatitude() {
        return get("DestLatitude");
    }

    @JSONField(name = "DestArea")
    public void setDestArea(String DestArea) {
        set("DestArea", DestArea);
    }

    @JSONField(name = "DestArea")
    public String getDestArea() {
        return get("DestArea");
    }

    @JSONField(name = "DestTime")
    public void setDestTime(Long DestTime) {
        set("DestTime", DestTime);
    }

    @JSONField(name = "DestTime")
    public Long getDestTime() {
        return get("DestTime");
    }

    @JSONField(name = "BookModel")
    public void setBookModel(String BookModel) {
        set("BookModel", BookModel);
    }

    @JSONField(name = "BookModel")
    public String getBookModel() {
        return get("BookModel");
    }

    @JSONField(name = "Model")
    public void setModel(String Model) {
        set("Model", Model);
    }

    @JSONField(name = "Model")
    public String getModel() {
        return get("Model");
    }

    @JSONField(name = "DriveMile")
    public void setDriveMile(Long DriveMile) {
        set("DriveMile", DriveMile);
    }

    @JSONField(name = "DriveMile")
    public Long getDriveMile() {
        return get("DriveMile");
    }

    @JSONField(name = "DriveTime")
    public void setDriveTime(Long DriveTime) {
        set("DriveTime", DriveTime);
    }

    @JSONField(name = "DriveTime")
    public Long getDriveTime() {
        return get("DriveTime");
    }

    @JSONField(name = "WaitMile")
    public void setWaitMile(Long WaitMile) {
        set("WaitMile", WaitMile);
    }

    @JSONField(name = "WaitMile")
    public Long getWaitMile() {
        return get("WaitMile");
    }

    @JSONField(name = "FactPrice")
    public void setFactPrice(Long FactPrice) {
        set("FactPrice", FactPrice);
    }

    @JSONField(name = "FactPrice")
    public Long getFactPrice() {
        return get("FactPrice");
    }

    @JSONField(name = "Price")
    public void setPrice(Long Price) {
        set("Price", Price);
    }

    @JSONField(name = "Price")
    public Long getPrice() {
        return get("Price");
    }

    @JSONField(name = "CashPrice")
    public void setCashPrice(Long CashPrice) {
        set("CashPrice", CashPrice);
    }

    @JSONField(name = "CashPrice")
    public Long getCashPrice() {
        return get("CashPrice");
    }

    @JSONField(name = "LineName")
    public void setLineName(String LineName) {
        set("LineName", LineName);
    }

    @JSONField(name = "LineName")
    public String getLineName() {
        return get("LineName");
    }

    @JSONField(name = "LinePrice")
    public void setLinePrice(Long LinePrice) {
        set("LinePrice", LinePrice);
    }

    @JSONField(name = "LinePrice")
    public Long getLinePrice() {
        return get("LinePrice");
    }

    @JSONField(name = "PosName")
    public void setPosName(String PosName) {
        set("PosName", PosName);
    }

    @JSONField(name = "PosName")
    public String getPosName() {
        return get("PosName");
    }

    @JSONField(name = "PosPrice")
    public void setPosPrice(Long PosPrice) {
        set("PosPrice", PosPrice);
    }

    @JSONField(name = "PosPrice")
    public Long getPosPrice() {
        return get("PosPrice");
    }

    @JSONField(name = "BenfitPrice")
    public void setBenfitPrice(Long BenfitPrice) {
        set("BenfitPrice", BenfitPrice);
    }

    @JSONField(name = "BenfitPrice")
    public Long getBenfitPrice() {
        return get("BenfitPrice");
    }

    @JSONField(name = "BookTip")
    public void setBookTip(Long BookTip) {
        set("BookTip", BookTip);
    }

    @JSONField(name = "BookTip")
    public Long getBookTip() {
        return get("BookTip");
    }

    @JSONField(name = "PassengerTip")
    public void setPassengerTip(Long PassengerTip) {
        set("PassengerTip", PassengerTip);
    }

    @JSONField(name = "PassengerTip")
    public Long getPassengerTip() {
        return get("PassengerTip");
    }

    @JSONField(name = "PeakUpPrice")
    public void setPeakUpPrice(Long PeakUpPrice) {
        set("PeakUpPrice", PeakUpPrice);
    }

    @JSONField(name = "PeakUpPrice")
    public Long getPeakUpPrice() {
        return get("PeakUpPrice");
    }

    @JSONField(name = "NightUpPrice")
    public void setNightUpPrice(Long NightUpPrice) {
        set("NightUpPrice", NightUpPrice);
    }

    @JSONField(name = "NightUpPrice")
    public Long getNightUpPrice() {
        return get("NightUpPrice");
    }

    @JSONField(name = "FarUpPrice")
    public void setFarUpPrice(Long FarUpPrice) {
        set("FarUpPrice", FarUpPrice);
    }

    @JSONField(name = "FarUpPrice")
    public Long getFarUpPrice() {
        return get("FarUpPrice");
    }

    @JSONField(name = "OtherUpPrice")
    public void setOtherUpPrice(Long OtherUpPrice) {
        set("OtherUpPrice", OtherUpPrice);
    }

    @JSONField(name = "OtherUpPrice")
    public Long getOtherUpPrice() {
        return get("OtherUpPrice");
    }

    @JSONField(name = "PayState")
    public void setPayState(String PayState) {
        set("PayState", PayState);
    }

    @JSONField(name = "PayState")
    public String getPayState() {
        return get("PayState");
    }

    @JSONField(name = "PayTime")
    public void setPayTime(Long PayTime) {
        set("PayTime", PayTime);
    }

    @JSONField(name = "PayTime")
    public Long getPayTime() {
        return get("PayTime");
    }

    @JSONField(name = "OrderMatchTime")
    public void setOrderMatchTime(Long OrderMatchTime) {
        set("OrderMatchTime", OrderMatchTime);
    }

    @JSONField(name = "OrderMatchTime")
    public Long getOrderMatchTime() {
        return get("OrderMatchTime");
    }

    @JSONField(name = "InvoiceStatus")
    public void setInvoiceStatus(String InvoiceStatus) {
        set("InvoiceStatus", InvoiceStatus);
    }

    @JSONField(name = "InvoiceStatus")
    public String getInvoiceStatus() {
        return get("InvoiceStatus");
    }

}
